// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="seven_segment_seven_segment,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.946250,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=117,HLS_SYN_LUT=328,HLS_VERSION=2022_2}" *)

module seven_segment (
        ap_clk,
        ap_rst,
        value_r,
        seg_tens,
        seg_ones
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input  [6:0] value_r;
output  [7:0] seg_tens;
output  [7:0] seg_ones;

reg[7:0] seg_tens;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln1035_fu_161_p2;
reg   [0:0] icmp_ln1035_reg_258;
reg   [3:0] tens_V_reg_262;
reg   [6:0] ap_phi_mux_r_V_phi_fu_114_p22;
wire    ap_CS_fsm_state11;
wire   [7:0] p_Result_1_fu_244_p3;
reg   [7:0] ap_phi_mux_storemerge_phi_fu_153_p4;
reg   [7:0] storemerge_reg_149;
wire   [7:0] p_Result_s_fu_197_p3;
wire   [6:0] mul_ln1513_fu_171_p0;
wire   [8:0] mul_ln1513_fu_171_p1;
wire   [14:0] mul_ln1513_fu_171_p2;
wire   [4:0] grp_fu_187_p1;
wire   [3:0] grp_fu_187_p2;
wire   [3:0] r_V_1_fu_206_p17;
wire   [6:0] r_V_1_fu_206_p18;
reg    grp_fu_187_ap_start;
wire    grp_fu_187_ap_done;
reg   [10:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire   [14:0] mul_ln1513_fu_171_p00;
reg    ap_condition_263;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

seven_segment_mul_7ns_9ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 15 ))
mul_7ns_9ns_15_1_1_U1(
    .din0(mul_ln1513_fu_171_p0),
    .din1(mul_ln1513_fu_171_p1),
    .dout(mul_ln1513_fu_171_p2)
);

seven_segment_urem_7ns_5ns_4_11_seq_1 #(
    .ID( 1 ),
    .NUM_STAGE( 11 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_7ns_5ns_4_11_seq_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .start(grp_fu_187_ap_start),
    .done(grp_fu_187_ap_done),
    .din0(value_r),
    .din1(grp_fu_187_p1),
    .ce(1'b1),
    .dout(grp_fu_187_p2)
);

seven_segment_mux_164_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 7 ),
    .din9_WIDTH( 7 ),
    .din10_WIDTH( 7 ),
    .din11_WIDTH( 7 ),
    .din12_WIDTH( 7 ),
    .din13_WIDTH( 7 ),
    .din14_WIDTH( 7 ),
    .din15_WIDTH( 7 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
mux_164_7_1_1_U3(
    .din0(7'd1),
    .din1(7'd79),
    .din2(7'd18),
    .din3(7'd6),
    .din4(7'd76),
    .din5(7'd36),
    .din6(7'd32),
    .din7(7'd15),
    .din8(7'd0),
    .din9(7'd4),
    .din10(7'd127),
    .din11(7'd127),
    .din12(7'd127),
    .din13(7'd127),
    .din14(7'd127),
    .din15(7'd127),
    .din16(r_V_1_fu_206_p17),
    .dout(r_V_1_fu_206_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1035_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                storemerge_reg_149[0] <= 1'b1;
        storemerge_reg_149[1] <= 1'b1;
        storemerge_reg_149[2] <= 1'b1;
        storemerge_reg_149[3] <= 1'b1;
        storemerge_reg_149[4] <= 1'b1;
        storemerge_reg_149[5] <= 1'b1;
        storemerge_reg_149[6] <= 1'b1;
    end else if (((icmp_ln1035_reg_258 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
                storemerge_reg_149[6 : 0] <= p_Result_1_fu_244_p3[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln1035_reg_258 <= icmp_ln1035_fu_161_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1035_fu_161_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        tens_V_reg_262 <= {{mul_ln1513_fu_171_p2[14:11]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln1035_reg_258 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        if ((tens_V_reg_262 == 4'd9)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd4;
        end else if ((tens_V_reg_262 == 4'd0)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd1;
        end else if ((tens_V_reg_262 == 4'd1)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd79;
        end else if ((tens_V_reg_262 == 4'd2)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd18;
        end else if ((tens_V_reg_262 == 4'd3)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd6;
        end else if ((tens_V_reg_262 == 4'd4)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd76;
        end else if ((tens_V_reg_262 == 4'd5)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd36;
        end else if ((tens_V_reg_262 == 4'd6)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd32;
        end else if ((tens_V_reg_262 == 4'd7)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd15;
        end else if ((tens_V_reg_262 == 4'd8)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd0;
        end else if ((1'b1 == ap_condition_263)) begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 7'd127;
        end else begin
            ap_phi_mux_r_V_phi_fu_114_p22 = 'bx;
        end
    end else begin
        ap_phi_mux_r_V_phi_fu_114_p22 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln1035_reg_258 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_storemerge_phi_fu_153_p4 = p_Result_1_fu_244_p3;
    end else begin
        ap_phi_mux_storemerge_phi_fu_153_p4 = storemerge_reg_149;
    end
end

always @ (*) begin
    if (((icmp_ln1035_fu_161_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_fu_187_ap_start = 1'b1;
    end else begin
        grp_fu_187_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1035_reg_258 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        seg_tens = p_Result_s_fu_197_p3;
    end else if (((icmp_ln1035_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        seg_tens = 8'd255;
    end else begin
        seg_tens = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln1035_fu_161_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

always @ (*) begin
    ap_condition_263 = (~(tens_V_reg_262 == 4'd9) & ~(tens_V_reg_262 == 4'd8) & ~(tens_V_reg_262 == 4'd7) & ~(tens_V_reg_262 == 4'd6) & ~(tens_V_reg_262 == 4'd5) & ~(tens_V_reg_262 == 4'd4) & ~(tens_V_reg_262 == 4'd3) & ~(tens_V_reg_262 == 4'd2) & ~(tens_V_reg_262 == 4'd1) & ~(tens_V_reg_262 == 4'd0));
end

assign grp_fu_187_p1 = 7'd10;

assign icmp_ln1035_fu_161_p2 = ((value_r > 7'd99) ? 1'b1 : 1'b0);

assign mul_ln1513_fu_171_p0 = mul_ln1513_fu_171_p00;

assign mul_ln1513_fu_171_p00 = value_r;

assign mul_ln1513_fu_171_p1 = 15'd205;

assign p_Result_1_fu_244_p3 = {{1'd1}, {r_V_1_fu_206_p18}};

assign p_Result_s_fu_197_p3 = {{1'd1}, {ap_phi_mux_r_V_phi_fu_114_p22}};

assign r_V_1_fu_206_p17 = grp_fu_187_p2[3:0];

assign seg_ones = ap_phi_mux_storemerge_phi_fu_153_p4;

always @ (posedge ap_clk) begin
    storemerge_reg_149[7] <= 1'b1;
end

endmodule //seven_segment
