-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity seven_segment is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    value_r : IN STD_LOGIC_VECTOR (13 downto 0);
    seg : OUT STD_LOGIC_VECTOR (7 downto 0);
    an : OUT STD_LOGIC_VECTOR (3 downto 0) );
end;


architecture behav of seven_segment is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "seven_segment_seven_segment,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=8.972000,HLS_SYN_LAT=34,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1568,HLS_SYN_LUT=1169,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_78 : STD_LOGIC_VECTOR (6 downto 0) := "1111000";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_const_lv7_12 : STD_LOGIC_VECTOR (6 downto 0) := "0010010";
    constant ap_const_lv7_19 : STD_LOGIC_VECTOR (6 downto 0) := "0011001";
    constant ap_const_lv7_30 : STD_LOGIC_VECTOR (6 downto 0) := "0110000";
    constant ap_const_lv7_24 : STD_LOGIC_VECTOR (6 downto 0) := "0100100";
    constant ap_const_lv7_79 : STD_LOGIC_VECTOR (6 downto 0) := "1111001";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_10 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv16_C34F : STD_LOGIC_VECTOR (15 downto 0) := "1100001101001111";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv14_3E7 : STD_LOGIC_VECTOR (13 downto 0) := "00001111100111";
    constant ap_const_lv14_63 : STD_LOGIC_VECTOR (13 downto 0) := "00000001100011";
    constant ap_const_lv14_9 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv8_A : STD_LOGIC_VECTOR (7 downto 0) := "00001010";
    constant ap_const_lv8_64 : STD_LOGIC_VECTOR (7 downto 0) := "01100100";
    constant ap_const_lv8_E8 : STD_LOGIC_VECTOR (7 downto 0) := "11101000";
    constant ap_const_lv14_A : STD_LOGIC_VECTOR (13 downto 0) := "00000000001010";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";

    signal tick_V : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal pos_V : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal pos_V_loc_0_reg_136 : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter17 : BOOLEAN;
    signal ap_block_state19_pp0_stage0_iter18 : BOOLEAN;
    signal ap_block_state20_pp0_stage0_iter19 : BOOLEAN;
    signal ap_block_state21_pp0_stage0_iter20 : BOOLEAN;
    signal ap_block_state22_pp0_stage0_iter21 : BOOLEAN;
    signal ap_block_state23_pp0_stage0_iter22 : BOOLEAN;
    signal ap_block_state24_pp0_stage0_iter23 : BOOLEAN;
    signal ap_block_state25_pp0_stage0_iter24 : BOOLEAN;
    signal ap_block_state26_pp0_stage0_iter25 : BOOLEAN;
    signal ap_block_state27_pp0_stage0_iter26 : BOOLEAN;
    signal ap_block_state28_pp0_stage0_iter27 : BOOLEAN;
    signal ap_block_state29_pp0_stage0_iter28 : BOOLEAN;
    signal ap_block_state30_pp0_stage0_iter29 : BOOLEAN;
    signal ap_block_state31_pp0_stage0_iter30 : BOOLEAN;
    signal ap_block_state32_pp0_stage0_iter31 : BOOLEAN;
    signal ap_block_state33_pp0_stage0_iter32 : BOOLEAN;
    signal ap_block_state34_pp0_stage0_iter33 : BOOLEAN;
    signal ap_block_state35_pp0_stage0_iter34 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal pos_V_loc_0_reg_136_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter7_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter8_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter14_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter15_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter16_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter17_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter18_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter19_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter20_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter21_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter22_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter23_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter24_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter25_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter26_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter27_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter28_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter29_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter30_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter31_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter32_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal pos_V_loc_0_reg_136_pp0_iter33_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal value_r_read_reg_401 : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter1_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter2_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter3_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter4_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter5_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter6_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter7_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter8_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter9_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter10_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter11_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter12_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter13_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter14_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter15_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal value_r_read_reg_401_pp0_iter16_reg : STD_LOGIC_VECTOR (13 downto 0);
    signal icmp_ln1039_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter16_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter17_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter18_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter19_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter20_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter21_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter22_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter23_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter24_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter25_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter26_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter27_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter28_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter29_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter30_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter31_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter32_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1039_reg_415_pp0_iter33_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter17 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter18 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter19 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter20 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter21 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter22 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter23 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter24 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter25 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter26 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter27 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter28 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter29 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter30 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter31 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter32 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter33 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter34 : STD_LOGIC := '0';
    signal ap_phi_mux_pos_V_loc_0_phi_fu_139_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln186_fu_229_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_reg_pp0_iter0_pos_V_loc_0_reg_136 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln1019_fu_200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_r_V_phi_fu_149_p22 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_phi_reg_pp0_iter34_r_V_reg_146 : STD_LOGIC_VECTOR (6 downto 0);
    signal digit_fu_371_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_188_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_375_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter34_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter3_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter4_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter5_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter6_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter7_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter8_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter9_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter10_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter11_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter12_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter13_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter14_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter15_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter16_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter17_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter18_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter19_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter20_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter21_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter22_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter23_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter24_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter25_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter26_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter27_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter28_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter29_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter30_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter31_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter32_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter33_storemerge_reg_184 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln186_1_fu_211_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal msd_pos_V_fu_254_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1031_fu_242_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1031_1_fu_248_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1031_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln1031_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1031_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1031_fu_276_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal zext_ln92_fu_260_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln97_1_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln97_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln97_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln97_fu_310_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln97_1_fu_324_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln97_fu_332_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_340_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal msd_pos_V_1_fu_290_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln97_2_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_340_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_365_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal grp_fu_365_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_365_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln930_fu_384_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_V_1_fu_388_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_340_p10 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_condition_673 : BOOLEAN;
    signal ap_condition_238 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component seven_segment_udiv_14ns_10ns_14_18_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component seven_segment_urem_14ns_5ns_4_18_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    udiv_14ns_10ns_14_18_1_U1 : component seven_segment_udiv_14ns_10ns_14_18_1
    generic map (
        ID => 1,
        NUM_STAGE => 18,
        din0_WIDTH => 14,
        din1_WIDTH => 10,
        dout_WIDTH => 14)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => value_r,
        din1 => grp_fu_340_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_340_p2);

    urem_14ns_5ns_4_18_1_U2 : component seven_segment_urem_14ns_5ns_4_18_1
    generic map (
        ID => 1,
        NUM_STAGE => 18,
        din0_WIDTH => 14,
        din1_WIDTH => 5,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_365_p0,
        din1 => grp_fu_365_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_365_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter17_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter17 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter18_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter18 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter19_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter19 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter20_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter20 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter21_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter21 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter22_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter22 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter23_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter23 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter24_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter24 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter25_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter25 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter26_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter26 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter27_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter27 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter28_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter28 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter29_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter29 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter30_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter30 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter31_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter31 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter32_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter32 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter33_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter33 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter34_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter34 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_storemerge_reg_184_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_238)) then
                if ((icmp_ln1039_fu_346_p2 = ap_const_lv1_1)) then 
                    ap_phi_reg_pp0_iter1_storemerge_reg_184 <= ap_const_lv8_FF;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_storemerge_reg_184 <= ap_phi_reg_pp0_iter0_storemerge_reg_184;
                end if;
            end if; 
        end if;
    end process;

    pos_V_loc_0_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_238)) then
                if ((icmp_ln1019_fu_200_p2 = ap_const_lv1_0)) then 
                    pos_V_loc_0_reg_136 <= pos_V;
                elsif ((icmp_ln1019_fu_200_p2 = ap_const_lv1_1)) then 
                    pos_V_loc_0_reg_136 <= add_ln186_fu_229_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    pos_V_loc_0_reg_136 <= ap_phi_reg_pp0_iter0_pos_V_loc_0_reg_136;
                end if;
            end if; 
        end if;
    end process;

    tick_V_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_238)) then
                if ((icmp_ln1019_fu_200_p2 = ap_const_lv1_1)) then 
                    tick_V <= ap_const_lv16_0;
                elsif ((icmp_ln1019_fu_200_p2 = ap_const_lv1_0)) then 
                    tick_V <= add_ln186_1_fu_211_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter9 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter10_storemerge_reg_184 <= ap_phi_reg_pp0_iter9_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter10 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter11_storemerge_reg_184 <= ap_phi_reg_pp0_iter10_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter12_storemerge_reg_184 <= ap_phi_reg_pp0_iter11_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter13_storemerge_reg_184 <= ap_phi_reg_pp0_iter12_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter14_storemerge_reg_184 <= ap_phi_reg_pp0_iter13_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter15_storemerge_reg_184 <= ap_phi_reg_pp0_iter14_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter15 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter16_storemerge_reg_184 <= ap_phi_reg_pp0_iter15_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter17_storemerge_reg_184 <= ap_phi_reg_pp0_iter16_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter17 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter18_storemerge_reg_184 <= ap_phi_reg_pp0_iter17_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter18 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter19_storemerge_reg_184 <= ap_phi_reg_pp0_iter18_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter19 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter20_storemerge_reg_184 <= ap_phi_reg_pp0_iter19_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter20 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter21_storemerge_reg_184 <= ap_phi_reg_pp0_iter20_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter21 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter22_storemerge_reg_184 <= ap_phi_reg_pp0_iter21_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter22 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter23_storemerge_reg_184 <= ap_phi_reg_pp0_iter22_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter23 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter24_storemerge_reg_184 <= ap_phi_reg_pp0_iter23_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter24 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter25_storemerge_reg_184 <= ap_phi_reg_pp0_iter24_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter25 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter26_storemerge_reg_184 <= ap_phi_reg_pp0_iter25_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter26 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter27_storemerge_reg_184 <= ap_phi_reg_pp0_iter26_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter27 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter28_storemerge_reg_184 <= ap_phi_reg_pp0_iter27_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter28 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter29_storemerge_reg_184 <= ap_phi_reg_pp0_iter28_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter2_storemerge_reg_184 <= ap_phi_reg_pp0_iter1_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter29 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter30_storemerge_reg_184 <= ap_phi_reg_pp0_iter29_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter30 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter31_storemerge_reg_184 <= ap_phi_reg_pp0_iter30_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter31 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter32_storemerge_reg_184 <= ap_phi_reg_pp0_iter31_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter32 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter33_storemerge_reg_184 <= ap_phi_reg_pp0_iter32_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter33 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter34_storemerge_reg_184 <= ap_phi_reg_pp0_iter33_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_storemerge_reg_184 <= ap_phi_reg_pp0_iter2_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter4_storemerge_reg_184 <= ap_phi_reg_pp0_iter3_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter5_storemerge_reg_184 <= ap_phi_reg_pp0_iter4_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter6_storemerge_reg_184 <= ap_phi_reg_pp0_iter5_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter7_storemerge_reg_184 <= ap_phi_reg_pp0_iter6_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter8_storemerge_reg_184 <= ap_phi_reg_pp0_iter7_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter8 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter9_storemerge_reg_184 <= ap_phi_reg_pp0_iter8_storemerge_reg_184;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln1039_reg_415 <= icmp_ln1039_fu_346_p2;
                icmp_ln1039_reg_415_pp0_iter1_reg <= icmp_ln1039_reg_415;
                pos_V_loc_0_reg_136_pp0_iter1_reg <= pos_V_loc_0_reg_136;
                value_r_read_reg_401 <= value_r;
                value_r_read_reg_401_pp0_iter1_reg <= value_r_read_reg_401;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln1039_reg_415_pp0_iter10_reg <= icmp_ln1039_reg_415_pp0_iter9_reg;
                icmp_ln1039_reg_415_pp0_iter11_reg <= icmp_ln1039_reg_415_pp0_iter10_reg;
                icmp_ln1039_reg_415_pp0_iter12_reg <= icmp_ln1039_reg_415_pp0_iter11_reg;
                icmp_ln1039_reg_415_pp0_iter13_reg <= icmp_ln1039_reg_415_pp0_iter12_reg;
                icmp_ln1039_reg_415_pp0_iter14_reg <= icmp_ln1039_reg_415_pp0_iter13_reg;
                icmp_ln1039_reg_415_pp0_iter15_reg <= icmp_ln1039_reg_415_pp0_iter14_reg;
                icmp_ln1039_reg_415_pp0_iter16_reg <= icmp_ln1039_reg_415_pp0_iter15_reg;
                icmp_ln1039_reg_415_pp0_iter17_reg <= icmp_ln1039_reg_415_pp0_iter16_reg;
                icmp_ln1039_reg_415_pp0_iter18_reg <= icmp_ln1039_reg_415_pp0_iter17_reg;
                icmp_ln1039_reg_415_pp0_iter19_reg <= icmp_ln1039_reg_415_pp0_iter18_reg;
                icmp_ln1039_reg_415_pp0_iter20_reg <= icmp_ln1039_reg_415_pp0_iter19_reg;
                icmp_ln1039_reg_415_pp0_iter21_reg <= icmp_ln1039_reg_415_pp0_iter20_reg;
                icmp_ln1039_reg_415_pp0_iter22_reg <= icmp_ln1039_reg_415_pp0_iter21_reg;
                icmp_ln1039_reg_415_pp0_iter23_reg <= icmp_ln1039_reg_415_pp0_iter22_reg;
                icmp_ln1039_reg_415_pp0_iter24_reg <= icmp_ln1039_reg_415_pp0_iter23_reg;
                icmp_ln1039_reg_415_pp0_iter25_reg <= icmp_ln1039_reg_415_pp0_iter24_reg;
                icmp_ln1039_reg_415_pp0_iter26_reg <= icmp_ln1039_reg_415_pp0_iter25_reg;
                icmp_ln1039_reg_415_pp0_iter27_reg <= icmp_ln1039_reg_415_pp0_iter26_reg;
                icmp_ln1039_reg_415_pp0_iter28_reg <= icmp_ln1039_reg_415_pp0_iter27_reg;
                icmp_ln1039_reg_415_pp0_iter29_reg <= icmp_ln1039_reg_415_pp0_iter28_reg;
                icmp_ln1039_reg_415_pp0_iter2_reg <= icmp_ln1039_reg_415_pp0_iter1_reg;
                icmp_ln1039_reg_415_pp0_iter30_reg <= icmp_ln1039_reg_415_pp0_iter29_reg;
                icmp_ln1039_reg_415_pp0_iter31_reg <= icmp_ln1039_reg_415_pp0_iter30_reg;
                icmp_ln1039_reg_415_pp0_iter32_reg <= icmp_ln1039_reg_415_pp0_iter31_reg;
                icmp_ln1039_reg_415_pp0_iter33_reg <= icmp_ln1039_reg_415_pp0_iter32_reg;
                icmp_ln1039_reg_415_pp0_iter3_reg <= icmp_ln1039_reg_415_pp0_iter2_reg;
                icmp_ln1039_reg_415_pp0_iter4_reg <= icmp_ln1039_reg_415_pp0_iter3_reg;
                icmp_ln1039_reg_415_pp0_iter5_reg <= icmp_ln1039_reg_415_pp0_iter4_reg;
                icmp_ln1039_reg_415_pp0_iter6_reg <= icmp_ln1039_reg_415_pp0_iter5_reg;
                icmp_ln1039_reg_415_pp0_iter7_reg <= icmp_ln1039_reg_415_pp0_iter6_reg;
                icmp_ln1039_reg_415_pp0_iter8_reg <= icmp_ln1039_reg_415_pp0_iter7_reg;
                icmp_ln1039_reg_415_pp0_iter9_reg <= icmp_ln1039_reg_415_pp0_iter8_reg;
                pos_V_loc_0_reg_136_pp0_iter10_reg <= pos_V_loc_0_reg_136_pp0_iter9_reg;
                pos_V_loc_0_reg_136_pp0_iter11_reg <= pos_V_loc_0_reg_136_pp0_iter10_reg;
                pos_V_loc_0_reg_136_pp0_iter12_reg <= pos_V_loc_0_reg_136_pp0_iter11_reg;
                pos_V_loc_0_reg_136_pp0_iter13_reg <= pos_V_loc_0_reg_136_pp0_iter12_reg;
                pos_V_loc_0_reg_136_pp0_iter14_reg <= pos_V_loc_0_reg_136_pp0_iter13_reg;
                pos_V_loc_0_reg_136_pp0_iter15_reg <= pos_V_loc_0_reg_136_pp0_iter14_reg;
                pos_V_loc_0_reg_136_pp0_iter16_reg <= pos_V_loc_0_reg_136_pp0_iter15_reg;
                pos_V_loc_0_reg_136_pp0_iter17_reg <= pos_V_loc_0_reg_136_pp0_iter16_reg;
                pos_V_loc_0_reg_136_pp0_iter18_reg <= pos_V_loc_0_reg_136_pp0_iter17_reg;
                pos_V_loc_0_reg_136_pp0_iter19_reg <= pos_V_loc_0_reg_136_pp0_iter18_reg;
                pos_V_loc_0_reg_136_pp0_iter20_reg <= pos_V_loc_0_reg_136_pp0_iter19_reg;
                pos_V_loc_0_reg_136_pp0_iter21_reg <= pos_V_loc_0_reg_136_pp0_iter20_reg;
                pos_V_loc_0_reg_136_pp0_iter22_reg <= pos_V_loc_0_reg_136_pp0_iter21_reg;
                pos_V_loc_0_reg_136_pp0_iter23_reg <= pos_V_loc_0_reg_136_pp0_iter22_reg;
                pos_V_loc_0_reg_136_pp0_iter24_reg <= pos_V_loc_0_reg_136_pp0_iter23_reg;
                pos_V_loc_0_reg_136_pp0_iter25_reg <= pos_V_loc_0_reg_136_pp0_iter24_reg;
                pos_V_loc_0_reg_136_pp0_iter26_reg <= pos_V_loc_0_reg_136_pp0_iter25_reg;
                pos_V_loc_0_reg_136_pp0_iter27_reg <= pos_V_loc_0_reg_136_pp0_iter26_reg;
                pos_V_loc_0_reg_136_pp0_iter28_reg <= pos_V_loc_0_reg_136_pp0_iter27_reg;
                pos_V_loc_0_reg_136_pp0_iter29_reg <= pos_V_loc_0_reg_136_pp0_iter28_reg;
                pos_V_loc_0_reg_136_pp0_iter2_reg <= pos_V_loc_0_reg_136_pp0_iter1_reg;
                pos_V_loc_0_reg_136_pp0_iter30_reg <= pos_V_loc_0_reg_136_pp0_iter29_reg;
                pos_V_loc_0_reg_136_pp0_iter31_reg <= pos_V_loc_0_reg_136_pp0_iter30_reg;
                pos_V_loc_0_reg_136_pp0_iter32_reg <= pos_V_loc_0_reg_136_pp0_iter31_reg;
                pos_V_loc_0_reg_136_pp0_iter33_reg <= pos_V_loc_0_reg_136_pp0_iter32_reg;
                pos_V_loc_0_reg_136_pp0_iter3_reg <= pos_V_loc_0_reg_136_pp0_iter2_reg;
                pos_V_loc_0_reg_136_pp0_iter4_reg <= pos_V_loc_0_reg_136_pp0_iter3_reg;
                pos_V_loc_0_reg_136_pp0_iter5_reg <= pos_V_loc_0_reg_136_pp0_iter4_reg;
                pos_V_loc_0_reg_136_pp0_iter6_reg <= pos_V_loc_0_reg_136_pp0_iter5_reg;
                pos_V_loc_0_reg_136_pp0_iter7_reg <= pos_V_loc_0_reg_136_pp0_iter6_reg;
                pos_V_loc_0_reg_136_pp0_iter8_reg <= pos_V_loc_0_reg_136_pp0_iter7_reg;
                pos_V_loc_0_reg_136_pp0_iter9_reg <= pos_V_loc_0_reg_136_pp0_iter8_reg;
                value_r_read_reg_401_pp0_iter10_reg <= value_r_read_reg_401_pp0_iter9_reg;
                value_r_read_reg_401_pp0_iter11_reg <= value_r_read_reg_401_pp0_iter10_reg;
                value_r_read_reg_401_pp0_iter12_reg <= value_r_read_reg_401_pp0_iter11_reg;
                value_r_read_reg_401_pp0_iter13_reg <= value_r_read_reg_401_pp0_iter12_reg;
                value_r_read_reg_401_pp0_iter14_reg <= value_r_read_reg_401_pp0_iter13_reg;
                value_r_read_reg_401_pp0_iter15_reg <= value_r_read_reg_401_pp0_iter14_reg;
                value_r_read_reg_401_pp0_iter16_reg <= value_r_read_reg_401_pp0_iter15_reg;
                value_r_read_reg_401_pp0_iter2_reg <= value_r_read_reg_401_pp0_iter1_reg;
                value_r_read_reg_401_pp0_iter3_reg <= value_r_read_reg_401_pp0_iter2_reg;
                value_r_read_reg_401_pp0_iter4_reg <= value_r_read_reg_401_pp0_iter3_reg;
                value_r_read_reg_401_pp0_iter5_reg <= value_r_read_reg_401_pp0_iter4_reg;
                value_r_read_reg_401_pp0_iter6_reg <= value_r_read_reg_401_pp0_iter5_reg;
                value_r_read_reg_401_pp0_iter7_reg <= value_r_read_reg_401_pp0_iter6_reg;
                value_r_read_reg_401_pp0_iter8_reg <= value_r_read_reg_401_pp0_iter7_reg;
                value_r_read_reg_401_pp0_iter9_reg <= value_r_read_reg_401_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1019_fu_200_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1))) then
                pos_V <= add_ln186_fu_229_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln186_1_fu_211_p2 <= std_logic_vector(unsigned(tick_V) + unsigned(ap_const_lv16_1));
    add_ln186_fu_229_p2 <= std_logic_vector(unsigned(pos_V) + unsigned(ap_const_lv2_1));
    an <= (r_V_1_fu_388_p2 xor ap_const_lv4_F);
    and_ln1031_fu_270_p2 <= (xor_ln1031_fu_264_p2 and icmp_ln1031_1_fu_248_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter17 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state19_pp0_stage0_iter18 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state20_pp0_stage0_iter19 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state21_pp0_stage0_iter20 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state22_pp0_stage0_iter21 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state23_pp0_stage0_iter22 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state24_pp0_stage0_iter23 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state25_pp0_stage0_iter24 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state26_pp0_stage0_iter25 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state27_pp0_stage0_iter26 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state28_pp0_stage0_iter27 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state29_pp0_stage0_iter28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state30_pp0_stage0_iter29 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state31_pp0_stage0_iter30 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state32_pp0_stage0_iter31 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state33_pp0_stage0_iter32 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state34_pp0_stage0_iter33 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state35_pp0_stage0_iter34 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_238_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_238 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_const_logic_1));
    end process;


    ap_condition_673_assign_proc : process(digit_fu_371_p1)
    begin
                ap_condition_673 <= (not((digit_fu_371_p1 = ap_const_lv4_9)) and not((digit_fu_371_p1 = ap_const_lv4_8)) and not((digit_fu_371_p1 = ap_const_lv4_7)) and not((digit_fu_371_p1 = ap_const_lv4_6)) and not((digit_fu_371_p1 = ap_const_lv4_5)) and not((digit_fu_371_p1 = ap_const_lv4_4)) and not((digit_fu_371_p1 = ap_const_lv4_3)) and not((digit_fu_371_p1 = ap_const_lv4_2)) and not((digit_fu_371_p1 = ap_const_lv4_1)) and not((digit_fu_371_p1 = ap_const_lv4_0)));
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16, ap_enable_reg_pp0_iter17, ap_enable_reg_pp0_iter18, ap_enable_reg_pp0_iter19, ap_enable_reg_pp0_iter20, ap_enable_reg_pp0_iter21, ap_enable_reg_pp0_iter22, ap_enable_reg_pp0_iter23, ap_enable_reg_pp0_iter24, ap_enable_reg_pp0_iter25, ap_enable_reg_pp0_iter26, ap_enable_reg_pp0_iter27, ap_enable_reg_pp0_iter28, ap_enable_reg_pp0_iter29, ap_enable_reg_pp0_iter30, ap_enable_reg_pp0_iter31, ap_enable_reg_pp0_iter32, ap_enable_reg_pp0_iter33, ap_enable_reg_pp0_iter34)
    begin
        if (((ap_enable_reg_pp0_iter34 = ap_const_logic_0) and (ap_enable_reg_pp0_iter33 = ap_const_logic_0) and (ap_enable_reg_pp0_iter32 = ap_const_logic_0) and (ap_enable_reg_pp0_iter31 = ap_const_logic_0) and (ap_enable_reg_pp0_iter30 = ap_const_logic_0) and (ap_enable_reg_pp0_iter29 = ap_const_logic_0) and (ap_enable_reg_pp0_iter28 = ap_const_logic_0) and (ap_enable_reg_pp0_iter27 = ap_const_logic_0) and (ap_enable_reg_pp0_iter26 = ap_const_logic_0) and (ap_enable_reg_pp0_iter25 = ap_const_logic_0) and (ap_enable_reg_pp0_iter24 = ap_const_logic_0) and (ap_enable_reg_pp0_iter23 = ap_const_logic_0) and (ap_enable_reg_pp0_iter22 = ap_const_logic_0) and (ap_enable_reg_pp0_iter21 = ap_const_logic_0) and (ap_enable_reg_pp0_iter20 = ap_const_logic_0) and (ap_enable_reg_pp0_iter19 = ap_const_logic_0) and (ap_enable_reg_pp0_iter18 = ap_const_logic_0) and (ap_enable_reg_pp0_iter17 = ap_const_logic_0) and (ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_logic_1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_pos_V_loc_0_phi_fu_139_p4_assign_proc : process(pos_V, add_ln186_fu_229_p2, ap_phi_reg_pp0_iter0_pos_V_loc_0_reg_136, icmp_ln1019_fu_200_p2)
    begin
        if ((icmp_ln1019_fu_200_p2 = ap_const_lv1_0)) then 
            ap_phi_mux_pos_V_loc_0_phi_fu_139_p4 <= pos_V;
        elsif ((icmp_ln1019_fu_200_p2 = ap_const_lv1_1)) then 
            ap_phi_mux_pos_V_loc_0_phi_fu_139_p4 <= add_ln186_fu_229_p2;
        else 
            ap_phi_mux_pos_V_loc_0_phi_fu_139_p4 <= ap_phi_reg_pp0_iter0_pos_V_loc_0_reg_136;
        end if; 
    end process;


    ap_phi_mux_r_V_phi_fu_149_p22_assign_proc : process(icmp_ln1039_reg_415_pp0_iter33_reg, ap_phi_reg_pp0_iter34_r_V_reg_146, digit_fu_371_p1, ap_condition_673)
    begin
        if ((icmp_ln1039_reg_415_pp0_iter33_reg = ap_const_lv1_0)) then
            if ((digit_fu_371_p1 = ap_const_lv4_9)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_10;
            elsif ((digit_fu_371_p1 = ap_const_lv4_0)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_40;
            elsif ((digit_fu_371_p1 = ap_const_lv4_1)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_79;
            elsif ((digit_fu_371_p1 = ap_const_lv4_2)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_24;
            elsif ((digit_fu_371_p1 = ap_const_lv4_3)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_30;
            elsif ((digit_fu_371_p1 = ap_const_lv4_4)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_19;
            elsif ((digit_fu_371_p1 = ap_const_lv4_5)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_12;
            elsif ((digit_fu_371_p1 = ap_const_lv4_6)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_2;
            elsif ((digit_fu_371_p1 = ap_const_lv4_7)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_78;
            elsif ((digit_fu_371_p1 = ap_const_lv4_8)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_0;
            elsif ((ap_const_boolean_1 = ap_condition_673)) then 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_const_lv7_7F;
            else 
                ap_phi_mux_r_V_phi_fu_149_p22 <= ap_phi_reg_pp0_iter34_r_V_reg_146;
            end if;
        else 
            ap_phi_mux_r_V_phi_fu_149_p22 <= ap_phi_reg_pp0_iter34_r_V_reg_146;
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_188_p4_assign_proc : process(icmp_ln1039_reg_415_pp0_iter33_reg, p_Result_s_fu_375_p3, ap_phi_reg_pp0_iter34_storemerge_reg_184)
    begin
        if ((icmp_ln1039_reg_415_pp0_iter33_reg = ap_const_lv1_0)) then 
            ap_phi_mux_storemerge_phi_fu_188_p4 <= p_Result_s_fu_375_p3;
        else 
            ap_phi_mux_storemerge_phi_fu_188_p4 <= ap_phi_reg_pp0_iter34_storemerge_reg_184;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_pos_V_loc_0_reg_136 <= "XX";
    ap_phi_reg_pp0_iter0_storemerge_reg_184 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter34_r_V_reg_146 <= "XXXXXXX";
    ap_reset_idle_pp0 <= ap_const_logic_0;
    digit_fu_371_p1 <= grp_fu_365_p2(4 - 1 downto 0);
    grp_fu_340_p1 <= grp_fu_340_p10(10 - 1 downto 0);
    grp_fu_340_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sext_ln97_fu_332_p1),14));
    grp_fu_365_p0 <= 
        value_r_read_reg_401_pp0_iter16_reg when (icmp_ln97_2_fu_352_p2(0) = '1') else 
        grp_fu_340_p2;
    grp_fu_365_p1 <= ap_const_lv14_A(5 - 1 downto 0);
    icmp_ln1019_fu_200_p2 <= "1" when (tick_V = ap_const_lv16_C34F) else "0";
    icmp_ln1031_1_fu_248_p2 <= "1" when (unsigned(value_r) > unsigned(ap_const_lv14_63)) else "0";
    icmp_ln1031_fu_242_p2 <= "1" when (unsigned(value_r) > unsigned(ap_const_lv14_3E7)) else "0";
    icmp_ln1039_fu_346_p2 <= "1" when (unsigned(ap_phi_mux_pos_V_loc_0_phi_fu_139_p4) > unsigned(msd_pos_V_1_fu_290_p3)) else "0";
    icmp_ln97_1_fu_304_p2 <= "1" when (ap_phi_mux_pos_V_loc_0_phi_fu_139_p4 = ap_const_lv2_1) else "0";
    icmp_ln97_2_fu_352_p2 <= "1" when (pos_V_loc_0_reg_136_pp0_iter16_reg = ap_const_lv2_0) else "0";
    icmp_ln97_fu_298_p2 <= "1" when (ap_phi_mux_pos_V_loc_0_phi_fu_139_p4 = ap_const_lv2_2) else "0";
    msd_pos_V_1_fu_290_p3 <= 
        select_ln1031_fu_276_p3 when (or_ln1031_fu_284_p2(0) = '1') else 
        zext_ln92_fu_260_p1;
    msd_pos_V_fu_254_p2 <= "1" when (unsigned(value_r) > unsigned(ap_const_lv14_9)) else "0";
    or_ln1031_fu_284_p2 <= (icmp_ln1031_fu_242_p2 or and_ln1031_fu_270_p2);
    or_ln97_fu_318_p2 <= (icmp_ln97_fu_298_p2 or icmp_ln97_1_fu_304_p2);
    p_Result_s_fu_375_p3 <= (ap_const_lv1_1 & ap_phi_mux_r_V_phi_fu_149_p22);
    r_V_1_fu_388_p2 <= std_logic_vector(shift_left(unsigned(ap_const_lv4_1),to_integer(unsigned('0' & zext_ln930_fu_384_p1(4-1 downto 0)))));
    seg <= ap_phi_mux_storemerge_phi_fu_188_p4;
    select_ln1031_fu_276_p3 <= 
        ap_const_lv2_2 when (and_ln1031_fu_270_p2(0) = '1') else 
        ap_const_lv2_3;
    select_ln97_1_fu_324_p3 <= 
        select_ln97_fu_310_p3 when (or_ln97_fu_318_p2(0) = '1') else 
        ap_const_lv8_E8;
    select_ln97_fu_310_p3 <= 
        ap_const_lv8_A when (icmp_ln97_1_fu_304_p2(0) = '1') else 
        ap_const_lv8_64;
        sext_ln97_fu_332_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(select_ln97_1_fu_324_p3),10));

    xor_ln1031_fu_264_p2 <= (icmp_ln1031_fu_242_p2 xor ap_const_lv1_1);
    zext_ln92_fu_260_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(msd_pos_V_fu_254_p2),2));
    zext_ln930_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(pos_V_loc_0_reg_136_pp0_iter33_reg),4));
end behav;
