// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="seven_segment_axi_seven_segment_axi,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z007s-clg400-1,HLS_INPUT_CLOCK=20.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=12.285900,HLS_SYN_LAT=44,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=2469,HLS_SYN_LUT=1732,HLS_VERSION=2022_2}" *)

module seven_segment_axi (
        ap_clk,
        ap_rst_n,
        seg,
        an,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output  [7:0] seg;
output  [3:0] an;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;

 reg    ap_rst_n_inv;
wire   [6:0] op1;
wire   [6:0] op2;
wire   [1:0] op_sel;
reg   [15:0] tick_V;
reg   [1:0] pos_V;
reg   [1:0] pos_wide_reg_199;
reg   [1:0] pos_wide_reg_199_pp0_iter11_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_state26_pp0_stage0_iter25;
wire    ap_block_state27_pp0_stage0_iter26;
wire    ap_block_state28_pp0_stage0_iter27;
wire    ap_block_state29_pp0_stage0_iter28;
wire    ap_block_state30_pp0_stage0_iter29;
wire    ap_block_state31_pp0_stage0_iter30;
wire    ap_block_state32_pp0_stage0_iter31;
wire    ap_block_state33_pp0_stage0_iter32;
wire    ap_block_state34_pp0_stage0_iter33;
wire    ap_block_state35_pp0_stage0_iter34;
wire    ap_block_state36_pp0_stage0_iter35;
wire    ap_block_state37_pp0_stage0_iter36;
wire    ap_block_state38_pp0_stage0_iter37;
wire    ap_block_state39_pp0_stage0_iter38;
wire    ap_block_state40_pp0_stage0_iter39;
wire    ap_block_state41_pp0_stage0_iter40;
wire    ap_block_state42_pp0_stage0_iter41;
wire    ap_block_state43_pp0_stage0_iter42;
wire    ap_block_state44_pp0_stage0_iter43;
wire    ap_block_state45_pp0_stage0_iter44;
wire    ap_block_pp0_stage0_11001;
reg   [1:0] pos_wide_reg_199_pp0_iter12_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter13_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter14_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter15_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter16_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter17_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter18_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter19_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter20_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter21_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter22_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter23_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter24_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter25_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter26_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter27_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter28_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter29_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter30_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter31_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter32_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter33_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter34_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter35_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter36_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter37_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter38_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter39_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter40_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter41_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter42_reg;
reg   [1:0] pos_wide_reg_199_pp0_iter43_reg;
wire   [1:0] op_sel_read_read_fu_150_p2;
reg   [1:0] op_sel_read_reg_621;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg   [1:0] op_sel_read_reg_621_pp0_iter1_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter2_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter3_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter4_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter5_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter6_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter7_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter8_reg;
reg   [1:0] op_sel_read_reg_621_pp0_iter9_reg;
reg   [6:0] op2_read_reg_625;
reg   [6:0] op2_read_reg_625_pp0_iter1_reg;
reg   [6:0] op2_read_reg_625_pp0_iter2_reg;
reg   [6:0] op2_read_reg_625_pp0_iter3_reg;
reg   [6:0] op2_read_reg_625_pp0_iter4_reg;
reg   [6:0] op2_read_reg_625_pp0_iter5_reg;
reg   [6:0] op2_read_reg_625_pp0_iter6_reg;
reg   [6:0] op2_read_reg_625_pp0_iter7_reg;
reg   [6:0] op2_read_reg_625_pp0_iter8_reg;
reg   [6:0] op1_read_reg_633;
reg   [6:0] op1_read_reg_633_pp0_iter1_reg;
reg   [6:0] op1_read_reg_633_pp0_iter2_reg;
reg   [6:0] op1_read_reg_633_pp0_iter3_reg;
reg   [6:0] op1_read_reg_633_pp0_iter4_reg;
reg   [6:0] op1_read_reg_633_pp0_iter5_reg;
reg   [6:0] op1_read_reg_633_pp0_iter6_reg;
reg   [6:0] op1_read_reg_633_pp0_iter7_reg;
reg   [6:0] op1_read_reg_633_pp0_iter8_reg;
wire   [0:0] icmp_ln1019_fu_288_p2;
reg   [0:0] icmp_ln1019_reg_641;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter1_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter2_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter3_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter4_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter5_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter6_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter7_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter8_reg;
reg   [0:0] icmp_ln1019_reg_641_pp0_iter9_reg;
wire   [0:0] icmp_ln1019_1_fu_304_p2;
reg   [0:0] icmp_ln1019_1_reg_645;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter1_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter2_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter3_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter4_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter5_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter6_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter7_reg;
reg   [0:0] icmp_ln1019_1_reg_645_pp0_iter8_reg;
wire   [14:0] zext_ln63_1_fu_340_p1;
wire  signed [14:0] sext_ln63_fu_356_p1;
wire   [14:0] zext_ln63_fu_372_p1;
wire   [1:0] add_ln186_fu_380_p2;
wire   [0:0] negative_fu_397_p3;
reg   [0:0] negative_reg_674;
wire   [13:0] magnitude_V_2_fu_415_p3;
reg   [13:0] magnitude_V_2_reg_679;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter11_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter12_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter13_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter14_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter15_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter16_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter17_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter18_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter19_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter20_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter21_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter22_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter23_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter24_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter25_reg;
reg   [13:0] magnitude_V_2_reg_679_pp0_iter26_reg;
wire   [0:0] error_1_fu_492_p2;
reg   [0:0] error_1_reg_694;
reg   [0:0] error_1_reg_694_pp0_iter12_reg;
reg   [0:0] error_1_reg_694_pp0_iter13_reg;
reg   [0:0] error_1_reg_694_pp0_iter14_reg;
reg   [0:0] error_1_reg_694_pp0_iter15_reg;
reg   [0:0] error_1_reg_694_pp0_iter16_reg;
reg   [0:0] error_1_reg_694_pp0_iter17_reg;
reg   [0:0] error_1_reg_694_pp0_iter18_reg;
reg   [0:0] error_1_reg_694_pp0_iter19_reg;
reg   [0:0] error_1_reg_694_pp0_iter20_reg;
reg   [0:0] error_1_reg_694_pp0_iter21_reg;
reg   [0:0] error_1_reg_694_pp0_iter22_reg;
reg   [0:0] error_1_reg_694_pp0_iter23_reg;
reg   [0:0] error_1_reg_694_pp0_iter24_reg;
reg   [0:0] error_1_reg_694_pp0_iter25_reg;
reg   [0:0] error_1_reg_694_pp0_iter26_reg;
reg   [0:0] error_1_reg_694_pp0_iter27_reg;
reg   [0:0] error_1_reg_694_pp0_iter28_reg;
reg   [0:0] error_1_reg_694_pp0_iter29_reg;
reg   [0:0] error_1_reg_694_pp0_iter30_reg;
reg   [0:0] error_1_reg_694_pp0_iter31_reg;
reg   [0:0] error_1_reg_694_pp0_iter32_reg;
reg   [0:0] error_1_reg_694_pp0_iter33_reg;
reg   [0:0] error_1_reg_694_pp0_iter34_reg;
reg   [0:0] error_1_reg_694_pp0_iter35_reg;
reg   [0:0] error_1_reg_694_pp0_iter36_reg;
reg   [0:0] error_1_reg_694_pp0_iter37_reg;
reg   [0:0] error_1_reg_694_pp0_iter38_reg;
reg   [0:0] error_1_reg_694_pp0_iter39_reg;
reg   [0:0] error_1_reg_694_pp0_iter40_reg;
reg   [0:0] error_1_reg_694_pp0_iter41_reg;
reg   [0:0] error_1_reg_694_pp0_iter42_reg;
reg   [0:0] error_1_reg_694_pp0_iter43_reg;
wire   [0:0] icmp_ln1039_fu_546_p2;
reg   [0:0] icmp_ln1039_reg_698;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter12_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter13_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter14_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter15_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter16_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter17_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter18_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter19_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter20_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter21_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter22_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter23_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter24_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter25_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter26_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter27_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter28_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter29_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter30_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter31_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter32_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter33_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter34_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter35_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter36_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter37_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter38_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter39_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter40_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter41_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter42_reg;
reg   [0:0] icmp_ln1039_reg_698_pp0_iter43_reg;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_enable_reg_pp0_iter20;
reg    ap_enable_reg_pp0_iter21;
reg    ap_enable_reg_pp0_iter22;
reg    ap_enable_reg_pp0_iter23;
reg    ap_enable_reg_pp0_iter24;
reg    ap_enable_reg_pp0_iter25;
reg    ap_enable_reg_pp0_iter26;
reg    ap_enable_reg_pp0_iter27;
reg    ap_enable_reg_pp0_iter28;
reg    ap_enable_reg_pp0_iter29;
reg    ap_enable_reg_pp0_iter30;
reg    ap_enable_reg_pp0_iter31;
reg    ap_enable_reg_pp0_iter32;
reg    ap_enable_reg_pp0_iter33;
reg    ap_enable_reg_pp0_iter34;
reg    ap_enable_reg_pp0_iter35;
reg    ap_enable_reg_pp0_iter36;
reg    ap_enable_reg_pp0_iter37;
reg    ap_enable_reg_pp0_iter38;
reg    ap_enable_reg_pp0_iter39;
reg    ap_enable_reg_pp0_iter40;
reg    ap_enable_reg_pp0_iter41;
reg    ap_enable_reg_pp0_iter42;
reg    ap_enable_reg_pp0_iter43;
reg    ap_enable_reg_pp0_iter44;
reg   [14:0] ap_phi_mux_result_V_4_phi_fu_186_p10;
wire   [14:0] ap_phi_reg_pp0_iter0_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter1_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter2_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter3_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter4_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter5_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter6_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter7_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter8_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter9_result_V_4_reg_182;
reg   [14:0] ap_phi_reg_pp0_iter10_result_V_4_reg_182;
wire   [14:0] zext_ln63_2_fu_392_p1;
wire   [1:0] ap_phi_reg_pp0_iter0_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter1_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter2_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter3_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter4_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter5_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter6_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter7_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter8_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter9_pos_wide_reg_199;
reg   [1:0] ap_phi_reg_pp0_iter10_pos_wide_reg_199;
wire   [0:0] ap_phi_reg_pp0_iter0_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter1_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter2_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter3_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter4_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter5_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter6_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter7_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter8_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter9_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter10_error_reg_209;
reg   [0:0] ap_phi_reg_pp0_iter11_error_reg_209;
reg   [6:0] ap_phi_mux_r_V_phi_fu_234_p22;
wire   [6:0] ap_phi_reg_pp0_iter44_r_V_reg_231;
wire   [3:0] digit_fu_591_p1;
reg   [7:0] ap_phi_mux_storemerge4_phi_fu_274_p8;
wire   [7:0] p_Result_s_fu_595_p3;
reg   [7:0] ap_phi_reg_pp0_iter44_storemerge4_reg_269;
wire   [7:0] ap_phi_reg_pp0_iter0_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter1_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter2_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter3_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter4_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter5_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter6_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter7_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter8_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter9_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter10_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter11_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter12_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter13_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter14_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter15_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter16_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter17_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter18_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter19_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter20_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter21_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter22_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter23_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter24_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter25_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter26_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter27_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter28_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter29_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter30_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter31_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter32_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter33_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter34_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter35_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter36_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter37_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter38_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter39_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter40_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter41_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter42_storemerge4_reg_269;
reg   [7:0] ap_phi_reg_pp0_iter43_storemerge4_reg_269;
wire   [0:0] icmp_ln1019_2_fu_566_p2;
wire   [15:0] add_ln186_1_fu_310_p2;
wire    ap_block_pp0_stage0;
wire    ap_block_pp0_stage0_01001;
wire   [6:0] result_V_2_fu_334_p0;
wire   [6:0] result_V_2_fu_334_p1;
wire   [13:0] result_V_2_fu_334_p2;
wire   [7:0] zext_ln71_fu_344_p1;
wire   [7:0] zext_ln71_1_fu_347_p1;
wire   [7:0] result_V_1_fu_350_p2;
wire   [7:0] zext_ln68_1_fu_363_p1;
wire   [7:0] zext_ln68_fu_360_p1;
wire   [7:0] result_V_fu_366_p2;
wire   [6:0] grp_fu_294_p2;
wire   [13:0] magnitude_V_1_fu_405_p1;
wire   [13:0] magnitude_V_fu_409_p2;
wire   [0:0] icmp_ln115_1_fu_429_p2;
wire   [0:0] icmp_ln115_fu_423_p2;
wire   [0:0] or_ln115_fu_443_p2;
wire   [7:0] select_ln115_fu_435_p3;
wire   [7:0] select_ln115_1_fu_449_p3;
wire  signed [9:0] sext_ln115_fu_457_p1;
wire   [13:0] grp_fu_465_p0;
wire   [9:0] grp_fu_465_p1;
wire   [0:0] icmp_ln1035_1_fu_476_p2;
wire   [0:0] and_ln90_fu_481_p2;
wire   [0:0] or_ln90_fu_486_p2;
wire   [0:0] icmp_ln1035_fu_471_p2;
wire   [0:0] msd_pos_V_fu_503_p2;
wire   [0:0] icmp_ln1031_fu_498_p2;
wire   [0:0] xor_ln1035_fu_512_p2;
wire   [0:0] and_ln1031_fu_518_p2;
wire   [0:0] or_ln1031_fu_532_p2;
wire   [1:0] select_ln1031_fu_524_p3;
wire   [1:0] zext_ln108_fu_508_p1;
wire   [1:0] msd_pos_V_2_fu_538_p3;
wire   [2:0] zext_ln1495_fu_552_p1;
wire   [2:0] ret_V_1_fu_556_p2;
wire   [2:0] zext_ln1019_fu_562_p1;
wire   [0:0] icmp_ln115_2_fu_572_p2;
wire   [13:0] grp_fu_465_p2;
wire   [13:0] grp_fu_585_p0;
wire   [4:0] grp_fu_585_p1;
wire   [3:0] grp_fu_585_p2;
wire   [3:0] zext_ln930_fu_604_p1;
wire   [3:0] r_V_1_fu_608_p2;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [13:0] grp_fu_465_p10;
wire   [13:0] result_V_2_fu_334_p00;
wire   [13:0] result_V_2_fu_334_p10;
reg    ap_condition_1075;
reg    ap_condition_423;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 tick_V = 16'd0;
#0 pos_V = 2'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 ap_enable_reg_pp0_iter20 = 1'b0;
#0 ap_enable_reg_pp0_iter21 = 1'b0;
#0 ap_enable_reg_pp0_iter22 = 1'b0;
#0 ap_enable_reg_pp0_iter23 = 1'b0;
#0 ap_enable_reg_pp0_iter24 = 1'b0;
#0 ap_enable_reg_pp0_iter25 = 1'b0;
#0 ap_enable_reg_pp0_iter26 = 1'b0;
#0 ap_enable_reg_pp0_iter27 = 1'b0;
#0 ap_enable_reg_pp0_iter28 = 1'b0;
#0 ap_enable_reg_pp0_iter29 = 1'b0;
#0 ap_enable_reg_pp0_iter30 = 1'b0;
#0 ap_enable_reg_pp0_iter31 = 1'b0;
#0 ap_enable_reg_pp0_iter32 = 1'b0;
#0 ap_enable_reg_pp0_iter33 = 1'b0;
#0 ap_enable_reg_pp0_iter34 = 1'b0;
#0 ap_enable_reg_pp0_iter35 = 1'b0;
#0 ap_enable_reg_pp0_iter36 = 1'b0;
#0 ap_enable_reg_pp0_iter37 = 1'b0;
#0 ap_enable_reg_pp0_iter38 = 1'b0;
#0 ap_enable_reg_pp0_iter39 = 1'b0;
#0 ap_enable_reg_pp0_iter40 = 1'b0;
#0 ap_enable_reg_pp0_iter41 = 1'b0;
#0 ap_enable_reg_pp0_iter42 = 1'b0;
#0 ap_enable_reg_pp0_iter43 = 1'b0;
#0 ap_enable_reg_pp0_iter44 = 1'b0;
end

seven_segment_axi_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .op1(op1),
    .op2(op2),
    .op_sel(op_sel)
);

seven_segment_axi_udiv_7ns_7ns_7_11_1 #(
    .ID( 1 ),
    .NUM_STAGE( 11 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 7 ))
udiv_7ns_7ns_7_11_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(op1),
    .din1(op2),
    .ce(1'b1),
    .dout(grp_fu_294_p2)
);

seven_segment_axi_mul_7ns_7ns_14_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 14 ))
mul_7ns_7ns_14_1_1_U2(
    .din0(result_V_2_fu_334_p0),
    .din1(result_V_2_fu_334_p1),
    .dout(result_V_2_fu_334_p2)
);

seven_segment_axi_udiv_14ns_10ns_14_18_1 #(
    .ID( 1 ),
    .NUM_STAGE( 18 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 14 ))
udiv_14ns_10ns_14_18_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_465_p0),
    .din1(grp_fu_465_p1),
    .ce(1'b1),
    .dout(grp_fu_465_p2)
);

seven_segment_axi_urem_14ns_5ns_4_18_1 #(
    .ID( 1 ),
    .NUM_STAGE( 18 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_14ns_5ns_4_18_1_U4(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_585_p0),
    .din1(grp_fu_585_p1),
    .ce(1'b1),
    .dout(grp_fu_585_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter20 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter20 <= ap_enable_reg_pp0_iter19;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter21 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter21 <= ap_enable_reg_pp0_iter20;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter22 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter22 <= ap_enable_reg_pp0_iter21;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter23 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter23 <= ap_enable_reg_pp0_iter22;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter24 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter24 <= ap_enable_reg_pp0_iter23;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter25 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter25 <= ap_enable_reg_pp0_iter24;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter26 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter26 <= ap_enable_reg_pp0_iter25;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter27 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter27 <= ap_enable_reg_pp0_iter26;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter28 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter28 <= ap_enable_reg_pp0_iter27;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter29 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter29 <= ap_enable_reg_pp0_iter28;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter30 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter30 <= ap_enable_reg_pp0_iter29;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter31 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter31 <= ap_enable_reg_pp0_iter30;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter32 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter32 <= ap_enable_reg_pp0_iter31;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter33 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter33 <= ap_enable_reg_pp0_iter32;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter34 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter34 <= ap_enable_reg_pp0_iter33;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter35 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter35 <= ap_enable_reg_pp0_iter34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter36 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter36 <= ap_enable_reg_pp0_iter35;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter37 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter37 <= ap_enable_reg_pp0_iter36;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter38 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter38 <= ap_enable_reg_pp0_iter37;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter39 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter39 <= ap_enable_reg_pp0_iter38;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter40 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter40 <= ap_enable_reg_pp0_iter39;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter41 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter41 <= ap_enable_reg_pp0_iter40;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter42 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter42 <= ap_enable_reg_pp0_iter41;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter43 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter43 <= ap_enable_reg_pp0_iter42;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter44 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter44 <= ap_enable_reg_pp0_iter43;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (op_sel_read_reg_621_pp0_iter8_reg == 2'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (op_sel_read_reg_621_pp0_iter8_reg == 2'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (op_sel_read_reg_621_pp0_iter8_reg == 2'd2)))) begin
        ap_phi_reg_pp0_iter10_error_reg_209 <= 1'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_phi_reg_pp0_iter10_error_reg_209 <= ap_phi_reg_pp0_iter9_error_reg_209;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((icmp_ln1019_1_reg_645_pp0_iter8_reg == 1'd0)) begin
            ap_phi_reg_pp0_iter10_pos_wide_reg_199 <= pos_V;
        end else if ((icmp_ln1019_1_reg_645_pp0_iter8_reg == 1'd1)) begin
            ap_phi_reg_pp0_iter10_pos_wide_reg_199 <= add_ln186_fu_380_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_pos_wide_reg_199 <= ap_phi_reg_pp0_iter9_pos_wide_reg_199;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        if ((op_sel_read_reg_621_pp0_iter8_reg == 2'd0)) begin
            ap_phi_reg_pp0_iter10_result_V_4_reg_182 <= zext_ln63_fu_372_p1;
        end else if ((op_sel_read_reg_621_pp0_iter8_reg == 2'd1)) begin
            ap_phi_reg_pp0_iter10_result_V_4_reg_182 <= sext_ln63_fu_356_p1;
        end else if ((op_sel_read_reg_621_pp0_iter8_reg == 2'd2)) begin
            ap_phi_reg_pp0_iter10_result_V_4_reg_182 <= zext_ln63_1_fu_340_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter10_result_V_4_reg_182 <= ap_phi_reg_pp0_iter9_result_V_4_reg_182;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        if (((icmp_ln1019_reg_641_pp0_iter9_reg == 1'd0) & (op_sel_read_reg_621_pp0_iter9_reg == 2'd3))) begin
            ap_phi_reg_pp0_iter11_error_reg_209 <= 1'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter11_error_reg_209 <= ap_phi_reg_pp0_iter10_error_reg_209;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1019_2_fu_566_p2 == 1'd1) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln1039_fu_546_p2 == 1'd1) & (error_1_fu_492_p2 == 1'd0) & (negative_reg_674 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (error_1_fu_492_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter12_storemerge4_reg_269 <= 8'd191;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1) & (((icmp_ln1019_2_fu_566_p2 == 1'd0) & (icmp_ln1039_fu_546_p2 == 1'd1) & (error_1_fu_492_p2 == 1'd0)) | ((icmp_ln1039_fu_546_p2 == 1'd1) & (error_1_fu_492_p2 == 1'd0) & (negative_reg_674 == 1'd0))))) begin
        ap_phi_reg_pp0_iter12_storemerge4_reg_269 <= 8'd255;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        ap_phi_reg_pp0_iter12_storemerge4_reg_269 <= ap_phi_reg_pp0_iter11_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_423)) begin
        if (((icmp_ln1019_fu_288_p2 == 1'd1) & (op_sel_read_read_fu_150_p2 == 2'd3))) begin
            ap_phi_reg_pp0_iter1_error_reg_209 <= 1'd1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_error_reg_209 <= ap_phi_reg_pp0_iter0_error_reg_209;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_423)) begin
        if (((icmp_ln1019_fu_288_p2 == 1'd1) & (op_sel_read_read_fu_150_p2 == 2'd3))) begin
            ap_phi_reg_pp0_iter1_result_V_4_reg_182 <= 15'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_result_V_4_reg_182 <= ap_phi_reg_pp0_iter0_result_V_4_reg_182;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_423)) begin
        if ((icmp_ln1019_1_fu_304_p2 == 1'd1)) begin
            tick_V <= 16'd0;
        end else if ((icmp_ln1019_1_fu_304_p2 == 1'd0)) begin
            tick_V <= add_ln186_1_fu_310_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1))) begin
        ap_phi_reg_pp0_iter10_storemerge4_reg_269 <= ap_phi_reg_pp0_iter9_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1))) begin
        ap_phi_reg_pp0_iter11_storemerge4_reg_269 <= ap_phi_reg_pp0_iter10_storemerge4_reg_269;
        pos_wide_reg_199 <= ap_phi_reg_pp0_iter10_pos_wide_reg_199;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter12 == 1'b1))) begin
        ap_phi_reg_pp0_iter13_storemerge4_reg_269 <= ap_phi_reg_pp0_iter12_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        ap_phi_reg_pp0_iter14_storemerge4_reg_269 <= ap_phi_reg_pp0_iter13_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter14 == 1'b1))) begin
        ap_phi_reg_pp0_iter15_storemerge4_reg_269 <= ap_phi_reg_pp0_iter14_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter15 == 1'b1))) begin
        ap_phi_reg_pp0_iter16_storemerge4_reg_269 <= ap_phi_reg_pp0_iter15_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter16 == 1'b1))) begin
        ap_phi_reg_pp0_iter17_storemerge4_reg_269 <= ap_phi_reg_pp0_iter16_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter17 == 1'b1))) begin
        ap_phi_reg_pp0_iter18_storemerge4_reg_269 <= ap_phi_reg_pp0_iter17_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter18 == 1'b1))) begin
        ap_phi_reg_pp0_iter19_storemerge4_reg_269 <= ap_phi_reg_pp0_iter18_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pos_wide_reg_199 <= ap_phi_reg_pp0_iter0_pos_wide_reg_199;
        ap_phi_reg_pp0_iter1_storemerge4_reg_269 <= ap_phi_reg_pp0_iter0_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter19 == 1'b1))) begin
        ap_phi_reg_pp0_iter20_storemerge4_reg_269 <= ap_phi_reg_pp0_iter19_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter20 == 1'b1))) begin
        ap_phi_reg_pp0_iter21_storemerge4_reg_269 <= ap_phi_reg_pp0_iter20_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter21 == 1'b1))) begin
        ap_phi_reg_pp0_iter22_storemerge4_reg_269 <= ap_phi_reg_pp0_iter21_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter22 == 1'b1))) begin
        ap_phi_reg_pp0_iter23_storemerge4_reg_269 <= ap_phi_reg_pp0_iter22_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter23 == 1'b1))) begin
        ap_phi_reg_pp0_iter24_storemerge4_reg_269 <= ap_phi_reg_pp0_iter23_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter24 == 1'b1))) begin
        ap_phi_reg_pp0_iter25_storemerge4_reg_269 <= ap_phi_reg_pp0_iter24_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter25 == 1'b1))) begin
        ap_phi_reg_pp0_iter26_storemerge4_reg_269 <= ap_phi_reg_pp0_iter25_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter26 == 1'b1))) begin
        ap_phi_reg_pp0_iter27_storemerge4_reg_269 <= ap_phi_reg_pp0_iter26_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter27 == 1'b1))) begin
        ap_phi_reg_pp0_iter28_storemerge4_reg_269 <= ap_phi_reg_pp0_iter27_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter28 == 1'b1))) begin
        ap_phi_reg_pp0_iter29_storemerge4_reg_269 <= ap_phi_reg_pp0_iter28_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_error_reg_209 <= ap_phi_reg_pp0_iter1_error_reg_209;
        ap_phi_reg_pp0_iter2_pos_wide_reg_199 <= ap_phi_reg_pp0_iter1_pos_wide_reg_199;
        ap_phi_reg_pp0_iter2_result_V_4_reg_182 <= ap_phi_reg_pp0_iter1_result_V_4_reg_182;
        ap_phi_reg_pp0_iter2_storemerge4_reg_269 <= ap_phi_reg_pp0_iter1_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter29 == 1'b1))) begin
        ap_phi_reg_pp0_iter30_storemerge4_reg_269 <= ap_phi_reg_pp0_iter29_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter30 == 1'b1))) begin
        ap_phi_reg_pp0_iter31_storemerge4_reg_269 <= ap_phi_reg_pp0_iter30_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter31 == 1'b1))) begin
        ap_phi_reg_pp0_iter32_storemerge4_reg_269 <= ap_phi_reg_pp0_iter31_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter32 == 1'b1))) begin
        ap_phi_reg_pp0_iter33_storemerge4_reg_269 <= ap_phi_reg_pp0_iter32_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter33 == 1'b1))) begin
        ap_phi_reg_pp0_iter34_storemerge4_reg_269 <= ap_phi_reg_pp0_iter33_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter34 == 1'b1))) begin
        ap_phi_reg_pp0_iter35_storemerge4_reg_269 <= ap_phi_reg_pp0_iter34_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter35 == 1'b1))) begin
        ap_phi_reg_pp0_iter36_storemerge4_reg_269 <= ap_phi_reg_pp0_iter35_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter36 == 1'b1))) begin
        ap_phi_reg_pp0_iter37_storemerge4_reg_269 <= ap_phi_reg_pp0_iter36_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter37 == 1'b1))) begin
        ap_phi_reg_pp0_iter38_storemerge4_reg_269 <= ap_phi_reg_pp0_iter37_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter38 == 1'b1))) begin
        ap_phi_reg_pp0_iter39_storemerge4_reg_269 <= ap_phi_reg_pp0_iter38_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_error_reg_209 <= ap_phi_reg_pp0_iter2_error_reg_209;
        ap_phi_reg_pp0_iter3_pos_wide_reg_199 <= ap_phi_reg_pp0_iter2_pos_wide_reg_199;
        ap_phi_reg_pp0_iter3_result_V_4_reg_182 <= ap_phi_reg_pp0_iter2_result_V_4_reg_182;
        ap_phi_reg_pp0_iter3_storemerge4_reg_269 <= ap_phi_reg_pp0_iter2_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter39 == 1'b1))) begin
        ap_phi_reg_pp0_iter40_storemerge4_reg_269 <= ap_phi_reg_pp0_iter39_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter40 == 1'b1))) begin
        ap_phi_reg_pp0_iter41_storemerge4_reg_269 <= ap_phi_reg_pp0_iter40_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter41 == 1'b1))) begin
        ap_phi_reg_pp0_iter42_storemerge4_reg_269 <= ap_phi_reg_pp0_iter41_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter42 == 1'b1))) begin
        ap_phi_reg_pp0_iter43_storemerge4_reg_269 <= ap_phi_reg_pp0_iter42_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter43 == 1'b1))) begin
        ap_phi_reg_pp0_iter44_storemerge4_reg_269 <= ap_phi_reg_pp0_iter43_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_error_reg_209 <= ap_phi_reg_pp0_iter3_error_reg_209;
        ap_phi_reg_pp0_iter4_pos_wide_reg_199 <= ap_phi_reg_pp0_iter3_pos_wide_reg_199;
        ap_phi_reg_pp0_iter4_result_V_4_reg_182 <= ap_phi_reg_pp0_iter3_result_V_4_reg_182;
        ap_phi_reg_pp0_iter4_storemerge4_reg_269 <= ap_phi_reg_pp0_iter3_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_error_reg_209 <= ap_phi_reg_pp0_iter4_error_reg_209;
        ap_phi_reg_pp0_iter5_pos_wide_reg_199 <= ap_phi_reg_pp0_iter4_pos_wide_reg_199;
        ap_phi_reg_pp0_iter5_result_V_4_reg_182 <= ap_phi_reg_pp0_iter4_result_V_4_reg_182;
        ap_phi_reg_pp0_iter5_storemerge4_reg_269 <= ap_phi_reg_pp0_iter4_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_error_reg_209 <= ap_phi_reg_pp0_iter5_error_reg_209;
        ap_phi_reg_pp0_iter6_pos_wide_reg_199 <= ap_phi_reg_pp0_iter5_pos_wide_reg_199;
        ap_phi_reg_pp0_iter6_result_V_4_reg_182 <= ap_phi_reg_pp0_iter5_result_V_4_reg_182;
        ap_phi_reg_pp0_iter6_storemerge4_reg_269 <= ap_phi_reg_pp0_iter5_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_phi_reg_pp0_iter7_error_reg_209 <= ap_phi_reg_pp0_iter6_error_reg_209;
        ap_phi_reg_pp0_iter7_pos_wide_reg_199 <= ap_phi_reg_pp0_iter6_pos_wide_reg_199;
        ap_phi_reg_pp0_iter7_result_V_4_reg_182 <= ap_phi_reg_pp0_iter6_result_V_4_reg_182;
        ap_phi_reg_pp0_iter7_storemerge4_reg_269 <= ap_phi_reg_pp0_iter6_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1))) begin
        ap_phi_reg_pp0_iter8_error_reg_209 <= ap_phi_reg_pp0_iter7_error_reg_209;
        ap_phi_reg_pp0_iter8_pos_wide_reg_199 <= ap_phi_reg_pp0_iter7_pos_wide_reg_199;
        ap_phi_reg_pp0_iter8_result_V_4_reg_182 <= ap_phi_reg_pp0_iter7_result_V_4_reg_182;
        ap_phi_reg_pp0_iter8_storemerge4_reg_269 <= ap_phi_reg_pp0_iter7_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter8 == 1'b1))) begin
        ap_phi_reg_pp0_iter9_error_reg_209 <= ap_phi_reg_pp0_iter8_error_reg_209;
        ap_phi_reg_pp0_iter9_pos_wide_reg_199 <= ap_phi_reg_pp0_iter8_pos_wide_reg_199;
        ap_phi_reg_pp0_iter9_result_V_4_reg_182 <= ap_phi_reg_pp0_iter8_result_V_4_reg_182;
        ap_phi_reg_pp0_iter9_storemerge4_reg_269 <= ap_phi_reg_pp0_iter8_storemerge4_reg_269;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        error_1_reg_694 <= error_1_fu_492_p2;
        error_1_reg_694_pp0_iter12_reg <= error_1_reg_694;
        error_1_reg_694_pp0_iter13_reg <= error_1_reg_694_pp0_iter12_reg;
        error_1_reg_694_pp0_iter14_reg <= error_1_reg_694_pp0_iter13_reg;
        error_1_reg_694_pp0_iter15_reg <= error_1_reg_694_pp0_iter14_reg;
        error_1_reg_694_pp0_iter16_reg <= error_1_reg_694_pp0_iter15_reg;
        error_1_reg_694_pp0_iter17_reg <= error_1_reg_694_pp0_iter16_reg;
        error_1_reg_694_pp0_iter18_reg <= error_1_reg_694_pp0_iter17_reg;
        error_1_reg_694_pp0_iter19_reg <= error_1_reg_694_pp0_iter18_reg;
        error_1_reg_694_pp0_iter20_reg <= error_1_reg_694_pp0_iter19_reg;
        error_1_reg_694_pp0_iter21_reg <= error_1_reg_694_pp0_iter20_reg;
        error_1_reg_694_pp0_iter22_reg <= error_1_reg_694_pp0_iter21_reg;
        error_1_reg_694_pp0_iter23_reg <= error_1_reg_694_pp0_iter22_reg;
        error_1_reg_694_pp0_iter24_reg <= error_1_reg_694_pp0_iter23_reg;
        error_1_reg_694_pp0_iter25_reg <= error_1_reg_694_pp0_iter24_reg;
        error_1_reg_694_pp0_iter26_reg <= error_1_reg_694_pp0_iter25_reg;
        error_1_reg_694_pp0_iter27_reg <= error_1_reg_694_pp0_iter26_reg;
        error_1_reg_694_pp0_iter28_reg <= error_1_reg_694_pp0_iter27_reg;
        error_1_reg_694_pp0_iter29_reg <= error_1_reg_694_pp0_iter28_reg;
        error_1_reg_694_pp0_iter30_reg <= error_1_reg_694_pp0_iter29_reg;
        error_1_reg_694_pp0_iter31_reg <= error_1_reg_694_pp0_iter30_reg;
        error_1_reg_694_pp0_iter32_reg <= error_1_reg_694_pp0_iter31_reg;
        error_1_reg_694_pp0_iter33_reg <= error_1_reg_694_pp0_iter32_reg;
        error_1_reg_694_pp0_iter34_reg <= error_1_reg_694_pp0_iter33_reg;
        error_1_reg_694_pp0_iter35_reg <= error_1_reg_694_pp0_iter34_reg;
        error_1_reg_694_pp0_iter36_reg <= error_1_reg_694_pp0_iter35_reg;
        error_1_reg_694_pp0_iter37_reg <= error_1_reg_694_pp0_iter36_reg;
        error_1_reg_694_pp0_iter38_reg <= error_1_reg_694_pp0_iter37_reg;
        error_1_reg_694_pp0_iter39_reg <= error_1_reg_694_pp0_iter38_reg;
        error_1_reg_694_pp0_iter40_reg <= error_1_reg_694_pp0_iter39_reg;
        error_1_reg_694_pp0_iter41_reg <= error_1_reg_694_pp0_iter40_reg;
        error_1_reg_694_pp0_iter42_reg <= error_1_reg_694_pp0_iter41_reg;
        error_1_reg_694_pp0_iter43_reg <= error_1_reg_694_pp0_iter42_reg;
        icmp_ln1019_1_reg_645_pp0_iter2_reg <= icmp_ln1019_1_reg_645_pp0_iter1_reg;
        icmp_ln1019_1_reg_645_pp0_iter3_reg <= icmp_ln1019_1_reg_645_pp0_iter2_reg;
        icmp_ln1019_1_reg_645_pp0_iter4_reg <= icmp_ln1019_1_reg_645_pp0_iter3_reg;
        icmp_ln1019_1_reg_645_pp0_iter5_reg <= icmp_ln1019_1_reg_645_pp0_iter4_reg;
        icmp_ln1019_1_reg_645_pp0_iter6_reg <= icmp_ln1019_1_reg_645_pp0_iter5_reg;
        icmp_ln1019_1_reg_645_pp0_iter7_reg <= icmp_ln1019_1_reg_645_pp0_iter6_reg;
        icmp_ln1019_1_reg_645_pp0_iter8_reg <= icmp_ln1019_1_reg_645_pp0_iter7_reg;
        icmp_ln1019_reg_641_pp0_iter2_reg <= icmp_ln1019_reg_641_pp0_iter1_reg;
        icmp_ln1019_reg_641_pp0_iter3_reg <= icmp_ln1019_reg_641_pp0_iter2_reg;
        icmp_ln1019_reg_641_pp0_iter4_reg <= icmp_ln1019_reg_641_pp0_iter3_reg;
        icmp_ln1019_reg_641_pp0_iter5_reg <= icmp_ln1019_reg_641_pp0_iter4_reg;
        icmp_ln1019_reg_641_pp0_iter6_reg <= icmp_ln1019_reg_641_pp0_iter5_reg;
        icmp_ln1019_reg_641_pp0_iter7_reg <= icmp_ln1019_reg_641_pp0_iter6_reg;
        icmp_ln1019_reg_641_pp0_iter8_reg <= icmp_ln1019_reg_641_pp0_iter7_reg;
        icmp_ln1019_reg_641_pp0_iter9_reg <= icmp_ln1019_reg_641_pp0_iter8_reg;
        icmp_ln1039_reg_698_pp0_iter12_reg <= icmp_ln1039_reg_698;
        icmp_ln1039_reg_698_pp0_iter13_reg <= icmp_ln1039_reg_698_pp0_iter12_reg;
        icmp_ln1039_reg_698_pp0_iter14_reg <= icmp_ln1039_reg_698_pp0_iter13_reg;
        icmp_ln1039_reg_698_pp0_iter15_reg <= icmp_ln1039_reg_698_pp0_iter14_reg;
        icmp_ln1039_reg_698_pp0_iter16_reg <= icmp_ln1039_reg_698_pp0_iter15_reg;
        icmp_ln1039_reg_698_pp0_iter17_reg <= icmp_ln1039_reg_698_pp0_iter16_reg;
        icmp_ln1039_reg_698_pp0_iter18_reg <= icmp_ln1039_reg_698_pp0_iter17_reg;
        icmp_ln1039_reg_698_pp0_iter19_reg <= icmp_ln1039_reg_698_pp0_iter18_reg;
        icmp_ln1039_reg_698_pp0_iter20_reg <= icmp_ln1039_reg_698_pp0_iter19_reg;
        icmp_ln1039_reg_698_pp0_iter21_reg <= icmp_ln1039_reg_698_pp0_iter20_reg;
        icmp_ln1039_reg_698_pp0_iter22_reg <= icmp_ln1039_reg_698_pp0_iter21_reg;
        icmp_ln1039_reg_698_pp0_iter23_reg <= icmp_ln1039_reg_698_pp0_iter22_reg;
        icmp_ln1039_reg_698_pp0_iter24_reg <= icmp_ln1039_reg_698_pp0_iter23_reg;
        icmp_ln1039_reg_698_pp0_iter25_reg <= icmp_ln1039_reg_698_pp0_iter24_reg;
        icmp_ln1039_reg_698_pp0_iter26_reg <= icmp_ln1039_reg_698_pp0_iter25_reg;
        icmp_ln1039_reg_698_pp0_iter27_reg <= icmp_ln1039_reg_698_pp0_iter26_reg;
        icmp_ln1039_reg_698_pp0_iter28_reg <= icmp_ln1039_reg_698_pp0_iter27_reg;
        icmp_ln1039_reg_698_pp0_iter29_reg <= icmp_ln1039_reg_698_pp0_iter28_reg;
        icmp_ln1039_reg_698_pp0_iter30_reg <= icmp_ln1039_reg_698_pp0_iter29_reg;
        icmp_ln1039_reg_698_pp0_iter31_reg <= icmp_ln1039_reg_698_pp0_iter30_reg;
        icmp_ln1039_reg_698_pp0_iter32_reg <= icmp_ln1039_reg_698_pp0_iter31_reg;
        icmp_ln1039_reg_698_pp0_iter33_reg <= icmp_ln1039_reg_698_pp0_iter32_reg;
        icmp_ln1039_reg_698_pp0_iter34_reg <= icmp_ln1039_reg_698_pp0_iter33_reg;
        icmp_ln1039_reg_698_pp0_iter35_reg <= icmp_ln1039_reg_698_pp0_iter34_reg;
        icmp_ln1039_reg_698_pp0_iter36_reg <= icmp_ln1039_reg_698_pp0_iter35_reg;
        icmp_ln1039_reg_698_pp0_iter37_reg <= icmp_ln1039_reg_698_pp0_iter36_reg;
        icmp_ln1039_reg_698_pp0_iter38_reg <= icmp_ln1039_reg_698_pp0_iter37_reg;
        icmp_ln1039_reg_698_pp0_iter39_reg <= icmp_ln1039_reg_698_pp0_iter38_reg;
        icmp_ln1039_reg_698_pp0_iter40_reg <= icmp_ln1039_reg_698_pp0_iter39_reg;
        icmp_ln1039_reg_698_pp0_iter41_reg <= icmp_ln1039_reg_698_pp0_iter40_reg;
        icmp_ln1039_reg_698_pp0_iter42_reg <= icmp_ln1039_reg_698_pp0_iter41_reg;
        icmp_ln1039_reg_698_pp0_iter43_reg <= icmp_ln1039_reg_698_pp0_iter42_reg;
        magnitude_V_2_reg_679 <= magnitude_V_2_fu_415_p3;
        magnitude_V_2_reg_679_pp0_iter11_reg <= magnitude_V_2_reg_679;
        magnitude_V_2_reg_679_pp0_iter12_reg <= magnitude_V_2_reg_679_pp0_iter11_reg;
        magnitude_V_2_reg_679_pp0_iter13_reg <= magnitude_V_2_reg_679_pp0_iter12_reg;
        magnitude_V_2_reg_679_pp0_iter14_reg <= magnitude_V_2_reg_679_pp0_iter13_reg;
        magnitude_V_2_reg_679_pp0_iter15_reg <= magnitude_V_2_reg_679_pp0_iter14_reg;
        magnitude_V_2_reg_679_pp0_iter16_reg <= magnitude_V_2_reg_679_pp0_iter15_reg;
        magnitude_V_2_reg_679_pp0_iter17_reg <= magnitude_V_2_reg_679_pp0_iter16_reg;
        magnitude_V_2_reg_679_pp0_iter18_reg <= magnitude_V_2_reg_679_pp0_iter17_reg;
        magnitude_V_2_reg_679_pp0_iter19_reg <= magnitude_V_2_reg_679_pp0_iter18_reg;
        magnitude_V_2_reg_679_pp0_iter20_reg <= magnitude_V_2_reg_679_pp0_iter19_reg;
        magnitude_V_2_reg_679_pp0_iter21_reg <= magnitude_V_2_reg_679_pp0_iter20_reg;
        magnitude_V_2_reg_679_pp0_iter22_reg <= magnitude_V_2_reg_679_pp0_iter21_reg;
        magnitude_V_2_reg_679_pp0_iter23_reg <= magnitude_V_2_reg_679_pp0_iter22_reg;
        magnitude_V_2_reg_679_pp0_iter24_reg <= magnitude_V_2_reg_679_pp0_iter23_reg;
        magnitude_V_2_reg_679_pp0_iter25_reg <= magnitude_V_2_reg_679_pp0_iter24_reg;
        magnitude_V_2_reg_679_pp0_iter26_reg <= magnitude_V_2_reg_679_pp0_iter25_reg;
        negative_reg_674 <= ap_phi_mux_result_V_4_phi_fu_186_p10[32'd14];
        op1_read_reg_633_pp0_iter2_reg <= op1_read_reg_633_pp0_iter1_reg;
        op1_read_reg_633_pp0_iter3_reg <= op1_read_reg_633_pp0_iter2_reg;
        op1_read_reg_633_pp0_iter4_reg <= op1_read_reg_633_pp0_iter3_reg;
        op1_read_reg_633_pp0_iter5_reg <= op1_read_reg_633_pp0_iter4_reg;
        op1_read_reg_633_pp0_iter6_reg <= op1_read_reg_633_pp0_iter5_reg;
        op1_read_reg_633_pp0_iter7_reg <= op1_read_reg_633_pp0_iter6_reg;
        op1_read_reg_633_pp0_iter8_reg <= op1_read_reg_633_pp0_iter7_reg;
        op2_read_reg_625_pp0_iter2_reg <= op2_read_reg_625_pp0_iter1_reg;
        op2_read_reg_625_pp0_iter3_reg <= op2_read_reg_625_pp0_iter2_reg;
        op2_read_reg_625_pp0_iter4_reg <= op2_read_reg_625_pp0_iter3_reg;
        op2_read_reg_625_pp0_iter5_reg <= op2_read_reg_625_pp0_iter4_reg;
        op2_read_reg_625_pp0_iter6_reg <= op2_read_reg_625_pp0_iter5_reg;
        op2_read_reg_625_pp0_iter7_reg <= op2_read_reg_625_pp0_iter6_reg;
        op2_read_reg_625_pp0_iter8_reg <= op2_read_reg_625_pp0_iter7_reg;
        op_sel_read_reg_621_pp0_iter2_reg <= op_sel_read_reg_621_pp0_iter1_reg;
        op_sel_read_reg_621_pp0_iter3_reg <= op_sel_read_reg_621_pp0_iter2_reg;
        op_sel_read_reg_621_pp0_iter4_reg <= op_sel_read_reg_621_pp0_iter3_reg;
        op_sel_read_reg_621_pp0_iter5_reg <= op_sel_read_reg_621_pp0_iter4_reg;
        op_sel_read_reg_621_pp0_iter6_reg <= op_sel_read_reg_621_pp0_iter5_reg;
        op_sel_read_reg_621_pp0_iter7_reg <= op_sel_read_reg_621_pp0_iter6_reg;
        op_sel_read_reg_621_pp0_iter8_reg <= op_sel_read_reg_621_pp0_iter7_reg;
        op_sel_read_reg_621_pp0_iter9_reg <= op_sel_read_reg_621_pp0_iter8_reg;
        pos_wide_reg_199_pp0_iter11_reg <= pos_wide_reg_199;
        pos_wide_reg_199_pp0_iter12_reg <= pos_wide_reg_199_pp0_iter11_reg;
        pos_wide_reg_199_pp0_iter13_reg <= pos_wide_reg_199_pp0_iter12_reg;
        pos_wide_reg_199_pp0_iter14_reg <= pos_wide_reg_199_pp0_iter13_reg;
        pos_wide_reg_199_pp0_iter15_reg <= pos_wide_reg_199_pp0_iter14_reg;
        pos_wide_reg_199_pp0_iter16_reg <= pos_wide_reg_199_pp0_iter15_reg;
        pos_wide_reg_199_pp0_iter17_reg <= pos_wide_reg_199_pp0_iter16_reg;
        pos_wide_reg_199_pp0_iter18_reg <= pos_wide_reg_199_pp0_iter17_reg;
        pos_wide_reg_199_pp0_iter19_reg <= pos_wide_reg_199_pp0_iter18_reg;
        pos_wide_reg_199_pp0_iter20_reg <= pos_wide_reg_199_pp0_iter19_reg;
        pos_wide_reg_199_pp0_iter21_reg <= pos_wide_reg_199_pp0_iter20_reg;
        pos_wide_reg_199_pp0_iter22_reg <= pos_wide_reg_199_pp0_iter21_reg;
        pos_wide_reg_199_pp0_iter23_reg <= pos_wide_reg_199_pp0_iter22_reg;
        pos_wide_reg_199_pp0_iter24_reg <= pos_wide_reg_199_pp0_iter23_reg;
        pos_wide_reg_199_pp0_iter25_reg <= pos_wide_reg_199_pp0_iter24_reg;
        pos_wide_reg_199_pp0_iter26_reg <= pos_wide_reg_199_pp0_iter25_reg;
        pos_wide_reg_199_pp0_iter27_reg <= pos_wide_reg_199_pp0_iter26_reg;
        pos_wide_reg_199_pp0_iter28_reg <= pos_wide_reg_199_pp0_iter27_reg;
        pos_wide_reg_199_pp0_iter29_reg <= pos_wide_reg_199_pp0_iter28_reg;
        pos_wide_reg_199_pp0_iter30_reg <= pos_wide_reg_199_pp0_iter29_reg;
        pos_wide_reg_199_pp0_iter31_reg <= pos_wide_reg_199_pp0_iter30_reg;
        pos_wide_reg_199_pp0_iter32_reg <= pos_wide_reg_199_pp0_iter31_reg;
        pos_wide_reg_199_pp0_iter33_reg <= pos_wide_reg_199_pp0_iter32_reg;
        pos_wide_reg_199_pp0_iter34_reg <= pos_wide_reg_199_pp0_iter33_reg;
        pos_wide_reg_199_pp0_iter35_reg <= pos_wide_reg_199_pp0_iter34_reg;
        pos_wide_reg_199_pp0_iter36_reg <= pos_wide_reg_199_pp0_iter35_reg;
        pos_wide_reg_199_pp0_iter37_reg <= pos_wide_reg_199_pp0_iter36_reg;
        pos_wide_reg_199_pp0_iter38_reg <= pos_wide_reg_199_pp0_iter37_reg;
        pos_wide_reg_199_pp0_iter39_reg <= pos_wide_reg_199_pp0_iter38_reg;
        pos_wide_reg_199_pp0_iter40_reg <= pos_wide_reg_199_pp0_iter39_reg;
        pos_wide_reg_199_pp0_iter41_reg <= pos_wide_reg_199_pp0_iter40_reg;
        pos_wide_reg_199_pp0_iter42_reg <= pos_wide_reg_199_pp0_iter41_reg;
        pos_wide_reg_199_pp0_iter43_reg <= pos_wide_reg_199_pp0_iter42_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1019_1_reg_645 <= icmp_ln1019_1_fu_304_p2;
        icmp_ln1019_1_reg_645_pp0_iter1_reg <= icmp_ln1019_1_reg_645;
        icmp_ln1019_reg_641_pp0_iter1_reg <= icmp_ln1019_reg_641;
        op1_read_reg_633 <= op1;
        op1_read_reg_633_pp0_iter1_reg <= op1_read_reg_633;
        op2_read_reg_625 <= op2;
        op2_read_reg_625_pp0_iter1_reg <= op2_read_reg_625;
        op_sel_read_reg_621 <= op_sel;
        op_sel_read_reg_621_pp0_iter1_reg <= op_sel_read_reg_621;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (op_sel_read_read_fu_150_p2 == 2'd3))) begin
        icmp_ln1019_reg_641 <= icmp_ln1019_fu_288_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (error_1_fu_492_p2 == 1'd0))) begin
        icmp_ln1039_reg_698 <= icmp_ln1039_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter9 == 1'b1) & (icmp_ln1019_1_reg_645_pp0_iter8_reg == 1'd1))) begin
        pos_V <= add_ln186_fu_380_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter44 == 1'b0) & (ap_enable_reg_pp0_iter43 == 1'b0) & (ap_enable_reg_pp0_iter42 == 1'b0) & (ap_enable_reg_pp0_iter41 == 1'b0) & (ap_enable_reg_pp0_iter40 == 1'b0) & (ap_enable_reg_pp0_iter39 == 1'b0) & (ap_enable_reg_pp0_iter38 == 1'b0) & (ap_enable_reg_pp0_iter37 == 1'b0) & (ap_enable_reg_pp0_iter36 == 1'b0) & (ap_enable_reg_pp0_iter35 == 1'b0) & (ap_enable_reg_pp0_iter34 == 1'b0) & (ap_enable_reg_pp0_iter33 == 1'b0) & (ap_enable_reg_pp0_iter32 == 1'b0) & (ap_enable_reg_pp0_iter31 == 1'b0) & (ap_enable_reg_pp0_iter30 == 1'b0) & (ap_enable_reg_pp0_iter29 == 1'b0) & (ap_enable_reg_pp0_iter28 == 1'b0) & (ap_enable_reg_pp0_iter27 == 1'b0) & (ap_enable_reg_pp0_iter26 == 1'b0) & (ap_enable_reg_pp0_iter25 == 1'b0) & (ap_enable_reg_pp0_iter24 == 1'b0) & (ap_enable_reg_pp0_iter23 == 1'b0) & (ap_enable_reg_pp0_iter22 == 1'b0) & (ap_enable_reg_pp0_iter21 == 1'b0) & (ap_enable_reg_pp0_iter20 == 1'b0) & (ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1039_reg_698_pp0_iter43_reg == 1'd0) & (error_1_reg_694_pp0_iter43_reg == 1'd0))) begin
        if ((digit_fu_591_p1 == 4'd9)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd16;
        end else if ((digit_fu_591_p1 == 4'd0)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd64;
        end else if ((digit_fu_591_p1 == 4'd1)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd121;
        end else if ((digit_fu_591_p1 == 4'd2)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd36;
        end else if ((digit_fu_591_p1 == 4'd3)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd48;
        end else if ((digit_fu_591_p1 == 4'd4)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd25;
        end else if ((digit_fu_591_p1 == 4'd5)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd18;
        end else if ((digit_fu_591_p1 == 4'd6)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd2;
        end else if ((digit_fu_591_p1 == 4'd7)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd120;
        end else if ((digit_fu_591_p1 == 4'd8)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd0;
        end else if ((1'b1 == ap_condition_1075)) begin
            ap_phi_mux_r_V_phi_fu_234_p22 = 7'd127;
        end else begin
            ap_phi_mux_r_V_phi_fu_234_p22 = ap_phi_reg_pp0_iter44_r_V_reg_231;
        end
    end else begin
        ap_phi_mux_r_V_phi_fu_234_p22 = ap_phi_reg_pp0_iter44_r_V_reg_231;
    end
end

always @ (*) begin
    if (((icmp_ln1019_reg_641_pp0_iter9_reg == 1'd0) & (op_sel_read_reg_621_pp0_iter9_reg == 2'd3))) begin
        ap_phi_mux_result_V_4_phi_fu_186_p10 = zext_ln63_2_fu_392_p1;
    end else begin
        ap_phi_mux_result_V_4_phi_fu_186_p10 = ap_phi_reg_pp0_iter10_result_V_4_reg_182;
    end
end

always @ (*) begin
    if (((icmp_ln1039_reg_698_pp0_iter43_reg == 1'd0) & (error_1_reg_694_pp0_iter43_reg == 1'd0))) begin
        ap_phi_mux_storemerge4_phi_fu_274_p8 = p_Result_s_fu_595_p3;
    end else begin
        ap_phi_mux_storemerge4_phi_fu_274_p8 = ap_phi_reg_pp0_iter44_storemerge4_reg_269;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln186_1_fu_310_p2 = (tick_V + 16'd1);

assign add_ln186_fu_380_p2 = (pos_V + 2'd1);

assign an = (r_V_1_fu_608_p2 ^ 4'd15);

assign and_ln1031_fu_518_p2 = (xor_ln1035_fu_512_p2 & icmp_ln1031_fu_498_p2);

assign and_ln90_fu_481_p2 = (negative_reg_674 & icmp_ln1035_1_fu_476_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage0_iter25 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage0_iter26 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage0_iter27 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter28 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage0_iter29 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage0_iter30 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage0_iter31 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage0_iter32 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter33 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage0_iter34 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter35 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage0_iter36 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage0_iter37 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage0_iter38 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage0_iter39 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage0_iter40 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage0_iter41 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter42 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage0_iter43 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage0_iter44 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1075 = (~(digit_fu_591_p1 == 4'd9) & ~(digit_fu_591_p1 == 4'd8) & ~(digit_fu_591_p1 == 4'd7) & ~(digit_fu_591_p1 == 4'd6) & ~(digit_fu_591_p1 == 4'd5) & ~(digit_fu_591_p1 == 4'd4) & ~(digit_fu_591_p1 == 4'd3) & ~(digit_fu_591_p1 == 4'd2) & ~(digit_fu_591_p1 == 4'd1) & ~(digit_fu_591_p1 == 4'd0));
end

always @ (*) begin
    ap_condition_423 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_error_reg_209 = 'bx;

assign ap_phi_reg_pp0_iter0_pos_wide_reg_199 = 'bx;

assign ap_phi_reg_pp0_iter0_result_V_4_reg_182 = 'bx;

assign ap_phi_reg_pp0_iter0_storemerge4_reg_269 = 'bx;

assign ap_phi_reg_pp0_iter44_r_V_reg_231 = 'bx;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign digit_fu_591_p1 = grp_fu_585_p2[3:0];

assign error_1_fu_492_p2 = (or_ln90_fu_486_p2 | icmp_ln1035_fu_471_p2);

assign grp_fu_465_p0 = ((negative_fu_397_p3[0:0] == 1'b1) ? magnitude_V_fu_409_p2 : magnitude_V_1_fu_405_p1);

assign grp_fu_465_p1 = grp_fu_465_p10;

assign grp_fu_465_p10 = $unsigned(sext_ln115_fu_457_p1);

assign grp_fu_585_p0 = ((icmp_ln115_2_fu_572_p2[0:0] == 1'b1) ? magnitude_V_2_reg_679_pp0_iter26_reg : grp_fu_465_p2);

assign grp_fu_585_p1 = 14'd10;

assign icmp_ln1019_1_fu_304_p2 = ((tick_V == 16'd49999) ? 1'b1 : 1'b0);

assign icmp_ln1019_2_fu_566_p2 = ((ret_V_1_fu_556_p2 == zext_ln1019_fu_562_p1) ? 1'b1 : 1'b0);

assign icmp_ln1019_fu_288_p2 = ((op2 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln1031_fu_498_p2 = ((magnitude_V_2_reg_679 > 14'd99) ? 1'b1 : 1'b0);

assign icmp_ln1035_1_fu_476_p2 = ((magnitude_V_2_reg_679 > 14'd999) ? 1'b1 : 1'b0);

assign icmp_ln1035_fu_471_p2 = ((magnitude_V_2_reg_679 > 14'd9999) ? 1'b1 : 1'b0);

assign icmp_ln1039_fu_546_p2 = ((msd_pos_V_2_fu_538_p3 < pos_wide_reg_199) ? 1'b1 : 1'b0);

assign icmp_ln115_1_fu_429_p2 = ((ap_phi_reg_pp0_iter10_pos_wide_reg_199 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln115_2_fu_572_p2 = ((pos_wide_reg_199_pp0_iter26_reg == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln115_fu_423_p2 = ((ap_phi_reg_pp0_iter10_pos_wide_reg_199 == 2'd2) ? 1'b1 : 1'b0);

assign magnitude_V_1_fu_405_p1 = ap_phi_mux_result_V_4_phi_fu_186_p10[13:0];

assign magnitude_V_2_fu_415_p3 = ((negative_fu_397_p3[0:0] == 1'b1) ? magnitude_V_fu_409_p2 : magnitude_V_1_fu_405_p1);

assign magnitude_V_fu_409_p2 = (14'd0 - magnitude_V_1_fu_405_p1);

assign msd_pos_V_2_fu_538_p3 = ((or_ln1031_fu_532_p2[0:0] == 1'b1) ? select_ln1031_fu_524_p3 : zext_ln108_fu_508_p1);

assign msd_pos_V_fu_503_p2 = ((magnitude_V_2_reg_679 > 14'd9) ? 1'b1 : 1'b0);

assign negative_fu_397_p3 = ap_phi_mux_result_V_4_phi_fu_186_p10[32'd14];

assign op_sel_read_read_fu_150_p2 = op_sel;

assign or_ln1031_fu_532_p2 = (icmp_ln1035_1_fu_476_p2 | and_ln1031_fu_518_p2);

assign or_ln115_fu_443_p2 = (icmp_ln115_fu_423_p2 | icmp_ln115_1_fu_429_p2);

assign or_ln90_fu_486_p2 = (ap_phi_reg_pp0_iter11_error_reg_209 | and_ln90_fu_481_p2);

assign p_Result_s_fu_595_p3 = {{1'd1}, {ap_phi_mux_r_V_phi_fu_234_p22}};

assign r_V_1_fu_608_p2 = 4'd1 << zext_ln930_fu_604_p1;

assign result_V_1_fu_350_p2 = (zext_ln71_fu_344_p1 - zext_ln71_1_fu_347_p1);

assign result_V_2_fu_334_p0 = result_V_2_fu_334_p00;

assign result_V_2_fu_334_p00 = op2_read_reg_625_pp0_iter8_reg;

assign result_V_2_fu_334_p1 = result_V_2_fu_334_p10;

assign result_V_2_fu_334_p10 = op1_read_reg_633_pp0_iter8_reg;

assign result_V_fu_366_p2 = (zext_ln68_1_fu_363_p1 + zext_ln68_fu_360_p1);

assign ret_V_1_fu_556_p2 = (zext_ln1495_fu_552_p1 + 3'd1);

assign seg = ap_phi_mux_storemerge4_phi_fu_274_p8;

assign select_ln1031_fu_524_p3 = ((and_ln1031_fu_518_p2[0:0] == 1'b1) ? 2'd2 : 2'd3);

assign select_ln115_1_fu_449_p3 = ((or_ln115_fu_443_p2[0:0] == 1'b1) ? select_ln115_fu_435_p3 : 8'd232);

assign select_ln115_fu_435_p3 = ((icmp_ln115_1_fu_429_p2[0:0] == 1'b1) ? 8'd10 : 8'd100);

assign sext_ln115_fu_457_p1 = $signed(select_ln115_1_fu_449_p3);

assign sext_ln63_fu_356_p1 = $signed(result_V_1_fu_350_p2);

assign xor_ln1035_fu_512_p2 = (icmp_ln1035_1_fu_476_p2 ^ 1'd1);

assign zext_ln1019_fu_562_p1 = pos_wide_reg_199;

assign zext_ln108_fu_508_p1 = msd_pos_V_fu_503_p2;

assign zext_ln1495_fu_552_p1 = msd_pos_V_2_fu_538_p3;

assign zext_ln63_1_fu_340_p1 = result_V_2_fu_334_p2;

assign zext_ln63_2_fu_392_p1 = grp_fu_294_p2;

assign zext_ln63_fu_372_p1 = result_V_fu_366_p2;

assign zext_ln68_1_fu_363_p1 = op2_read_reg_625_pp0_iter8_reg;

assign zext_ln68_fu_360_p1 = op1_read_reg_633_pp0_iter8_reg;

assign zext_ln71_1_fu_347_p1 = op2_read_reg_625_pp0_iter8_reg;

assign zext_ln71_fu_344_p1 = op1_read_reg_633_pp0_iter8_reg;

assign zext_ln930_fu_604_p1 = pos_wide_reg_199_pp0_iter43_reg;

endmodule //seven_segment_axi
