-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity seven_segment is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    value_r : IN STD_LOGIC_VECTOR (6 downto 0);
    seg_tens : OUT STD_LOGIC_VECTOR (7 downto 0);
    seg_ones : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of seven_segment is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "seven_segment_seven_segment,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.946250,HLS_SYN_LAT=6,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=117,HLS_SYN_LUT=328,HLS_VERSION=2022_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_F : STD_LOGIC_VECTOR (6 downto 0) := "0001111";
    constant ap_const_lv7_20 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_const_lv7_24 : STD_LOGIC_VECTOR (6 downto 0) := "0100100";
    constant ap_const_lv7_4C : STD_LOGIC_VECTOR (6 downto 0) := "1001100";
    constant ap_const_lv7_6 : STD_LOGIC_VECTOR (6 downto 0) := "0000110";
    constant ap_const_lv7_12 : STD_LOGIC_VECTOR (6 downto 0) := "0010010";
    constant ap_const_lv7_4F : STD_LOGIC_VECTOR (6 downto 0) := "1001111";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_4 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_63 : STD_LOGIC_VECTOR (6 downto 0) := "1100011";
    constant ap_const_lv15_CD : STD_LOGIC_VECTOR (14 downto 0) := "000000011001101";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv7_A : STD_LOGIC_VECTOR (6 downto 0) := "0001010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln1035_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1035_reg_258 : STD_LOGIC_VECTOR (0 downto 0);
    signal tens_V_reg_262 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_r_V_phi_fu_114_p22 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal p_Result_1_fu_244_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_storemerge_phi_fu_153_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal storemerge_reg_149 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_s_fu_197_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal mul_ln1513_fu_171_p0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul_ln1513_fu_171_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln1513_fu_171_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal grp_fu_187_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_187_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_V_1_fu_206_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_V_1_fu_206_p18 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_187_ap_start : STD_LOGIC;
    signal grp_fu_187_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal mul_ln1513_fu_171_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_condition_263 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component seven_segment_mul_7ns_9ns_15_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        dout : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component seven_segment_urem_7ns_5ns_4_11_seq_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component seven_segment_mux_164_7_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        din9_WIDTH : INTEGER;
        din10_WIDTH : INTEGER;
        din11_WIDTH : INTEGER;
        din12_WIDTH : INTEGER;
        din13_WIDTH : INTEGER;
        din14_WIDTH : INTEGER;
        din15_WIDTH : INTEGER;
        din16_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (6 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (6 downto 0);
        din3 : IN STD_LOGIC_VECTOR (6 downto 0);
        din4 : IN STD_LOGIC_VECTOR (6 downto 0);
        din5 : IN STD_LOGIC_VECTOR (6 downto 0);
        din6 : IN STD_LOGIC_VECTOR (6 downto 0);
        din7 : IN STD_LOGIC_VECTOR (6 downto 0);
        din8 : IN STD_LOGIC_VECTOR (6 downto 0);
        din9 : IN STD_LOGIC_VECTOR (6 downto 0);
        din10 : IN STD_LOGIC_VECTOR (6 downto 0);
        din11 : IN STD_LOGIC_VECTOR (6 downto 0);
        din12 : IN STD_LOGIC_VECTOR (6 downto 0);
        din13 : IN STD_LOGIC_VECTOR (6 downto 0);
        din14 : IN STD_LOGIC_VECTOR (6 downto 0);
        din15 : IN STD_LOGIC_VECTOR (6 downto 0);
        din16 : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (6 downto 0) );
    end component;



begin
    mul_7ns_9ns_15_1_1_U1 : component seven_segment_mul_7ns_9ns_15_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 9,
        dout_WIDTH => 15)
    port map (
        din0 => mul_ln1513_fu_171_p0,
        din1 => mul_ln1513_fu_171_p1,
        dout => mul_ln1513_fu_171_p2);

    urem_7ns_5ns_4_11_seq_1_U2 : component seven_segment_urem_7ns_5ns_4_11_seq_1
    generic map (
        ID => 1,
        NUM_STAGE => 11,
        din0_WIDTH => 7,
        din1_WIDTH => 5,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_187_ap_start,
        done => grp_fu_187_ap_done,
        din0 => value_r,
        din1 => grp_fu_187_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_187_p2);

    mux_164_7_1_1_U3 : component seven_segment_mux_164_7_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 7,
        din1_WIDTH => 7,
        din2_WIDTH => 7,
        din3_WIDTH => 7,
        din4_WIDTH => 7,
        din5_WIDTH => 7,
        din6_WIDTH => 7,
        din7_WIDTH => 7,
        din8_WIDTH => 7,
        din9_WIDTH => 7,
        din10_WIDTH => 7,
        din11_WIDTH => 7,
        din12_WIDTH => 7,
        din13_WIDTH => 7,
        din14_WIDTH => 7,
        din15_WIDTH => 7,
        din16_WIDTH => 4,
        dout_WIDTH => 7)
    port map (
        din0 => ap_const_lv7_1,
        din1 => ap_const_lv7_4F,
        din2 => ap_const_lv7_12,
        din3 => ap_const_lv7_6,
        din4 => ap_const_lv7_4C,
        din5 => ap_const_lv7_24,
        din6 => ap_const_lv7_20,
        din7 => ap_const_lv7_F,
        din8 => ap_const_lv7_0,
        din9 => ap_const_lv7_4,
        din10 => ap_const_lv7_7F,
        din11 => ap_const_lv7_7F,
        din12 => ap_const_lv7_7F,
        din13 => ap_const_lv7_7F,
        din14 => ap_const_lv7_7F,
        din15 => ap_const_lv7_7F,
        din16 => r_V_1_fu_206_p17,
        dout => r_V_1_fu_206_p18);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    storemerge_reg_149_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1035_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                storemerge_reg_149(0) <= '1';
                storemerge_reg_149(1) <= '1';
                storemerge_reg_149(2) <= '1';
                storemerge_reg_149(3) <= '1';
                storemerge_reg_149(4) <= '1';
                storemerge_reg_149(5) <= '1';
                storemerge_reg_149(6) <= '1';
            elsif (((icmp_ln1035_reg_258 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                                storemerge_reg_149(6 downto 0) <= p_Result_1_fu_244_p3(6 downto 0);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                icmp_ln1035_reg_258 <= icmp_ln1035_fu_161_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln1035_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                tens_V_reg_262 <= mul_ln1513_fu_171_p2(14 downto 11);
            end if;
        end if;
    end process;
    storemerge_reg_149(7) <= '1';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, icmp_ln1035_fu_161_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln1035_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_condition_263_assign_proc : process(tens_V_reg_262)
    begin
                ap_condition_263 <= (not((tens_V_reg_262 = ap_const_lv4_9)) and not((tens_V_reg_262 = ap_const_lv4_8)) and not((tens_V_reg_262 = ap_const_lv4_7)) and not((tens_V_reg_262 = ap_const_lv4_6)) and not((tens_V_reg_262 = ap_const_lv4_5)) and not((tens_V_reg_262 = ap_const_lv4_4)) and not((tens_V_reg_262 = ap_const_lv4_3)) and not((tens_V_reg_262 = ap_const_lv4_2)) and not((tens_V_reg_262 = ap_const_lv4_1)) and not((tens_V_reg_262 = ap_const_lv4_0)));
    end process;


    ap_phi_mux_r_V_phi_fu_114_p22_assign_proc : process(icmp_ln1035_reg_258, tens_V_reg_262, ap_CS_fsm_state11, ap_condition_263)
    begin
        if (((icmp_ln1035_reg_258 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
            if ((tens_V_reg_262 = ap_const_lv4_9)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_4;
            elsif ((tens_V_reg_262 = ap_const_lv4_0)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_1;
            elsif ((tens_V_reg_262 = ap_const_lv4_1)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_4F;
            elsif ((tens_V_reg_262 = ap_const_lv4_2)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_12;
            elsif ((tens_V_reg_262 = ap_const_lv4_3)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_6;
            elsif ((tens_V_reg_262 = ap_const_lv4_4)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_4C;
            elsif ((tens_V_reg_262 = ap_const_lv4_5)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_24;
            elsif ((tens_V_reg_262 = ap_const_lv4_6)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_20;
            elsif ((tens_V_reg_262 = ap_const_lv4_7)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_F;
            elsif ((tens_V_reg_262 = ap_const_lv4_8)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_0;
            elsif ((ap_const_boolean_1 = ap_condition_263)) then 
                ap_phi_mux_r_V_phi_fu_114_p22 <= ap_const_lv7_7F;
            else 
                ap_phi_mux_r_V_phi_fu_114_p22 <= "XXXXXXX";
            end if;
        else 
            ap_phi_mux_r_V_phi_fu_114_p22 <= "XXXXXXX";
        end if; 
    end process;


    ap_phi_mux_storemerge_phi_fu_153_p4_assign_proc : process(icmp_ln1035_reg_258, ap_CS_fsm_state11, p_Result_1_fu_244_p3, storemerge_reg_149)
    begin
        if (((icmp_ln1035_reg_258 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_phi_mux_storemerge_phi_fu_153_p4 <= p_Result_1_fu_244_p3;
        else 
            ap_phi_mux_storemerge_phi_fu_153_p4 <= storemerge_reg_149;
        end if; 
    end process;


    grp_fu_187_ap_start_assign_proc : process(ap_CS_fsm_state1, icmp_ln1035_fu_161_p2)
    begin
        if (((icmp_ln1035_fu_161_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            grp_fu_187_ap_start <= ap_const_logic_1;
        else 
            grp_fu_187_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_187_p1 <= ap_const_lv7_A(5 - 1 downto 0);
    icmp_ln1035_fu_161_p2 <= "1" when (unsigned(value_r) > unsigned(ap_const_lv7_63)) else "0";
    mul_ln1513_fu_171_p0 <= mul_ln1513_fu_171_p00(7 - 1 downto 0);
    mul_ln1513_fu_171_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(value_r),15));
    mul_ln1513_fu_171_p1 <= ap_const_lv15_CD(9 - 1 downto 0);
    p_Result_1_fu_244_p3 <= (ap_const_lv1_1 & r_V_1_fu_206_p18);
    p_Result_s_fu_197_p3 <= (ap_const_lv1_1 & ap_phi_mux_r_V_phi_fu_114_p22);
    r_V_1_fu_206_p17 <= grp_fu_187_p2(4 - 1 downto 0);
    seg_ones <= ap_phi_mux_storemerge_phi_fu_153_p4;

    seg_tens_assign_proc : process(ap_CS_fsm_state1, icmp_ln1035_fu_161_p2, icmp_ln1035_reg_258, ap_CS_fsm_state11, p_Result_s_fu_197_p3)
    begin
        if (((icmp_ln1035_reg_258 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            seg_tens <= p_Result_s_fu_197_p3;
        elsif (((icmp_ln1035_fu_161_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            seg_tens <= ap_const_lv8_FF;
        else 
            seg_tens <= "XXXXXXXX";
        end if; 
    end process;

end behav;
