#!/usr/bin/env bash
#
# Copies the live Vitis HLS / Vivado / Vitis projects from the tool
# workspaces (~/vitis, ~/vivado) into the git-tracked lab tree.
#
# Tool-generated build artefacts are excluded: they are large, machine
# specific, and regenerated by re-running the flow. What is kept is the
# source, the project metadata needed to reopen the project, the synthesis
# reports, and the exported IP that the next lab stage consumes.
#
# Usage:
#   scripts/sync_projects_to_repo.sh            # copy/update (safe)
#   scripts/sync_projects_to_repo.sh --delete   # mirror exactly (removes
#                                               # repo files no longer in
#                                               # the live project)
#
# Run this on the remote server. Git operations happen on the host machine.

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LABS="$REPO/labs"

DELETE=()
if [ "${1:-}" = "--delete" ]; then
    DELETE=(--delete)
    echo "mirror mode: repo files missing from the live projects will be removed"
fi

# Vitis HLS: .autopilot is the tool's internal database (~9 MB per solution),
# csim/build holds compiled test binaries. Reports and impl/ip are kept.
HLS_EXCLUDES=(
    --exclude '.autopilot/'
    --exclude '.debug/'
    --exclude '.tcls/'
    --exclude 'csim/build/'
    --exclude '*.o'
    --exclude '.Xil/'
)

# Vivado: .gen/.runs/.cache/.hw/.sim are all regenerated by synthesis and
# implementation. The block design, constraints and .xpr are kept.
VIVADO_EXCLUDES=(
    --exclude '*.gen/'
    --exclude '*.runs/'
    --exclude '*.cache/'
    --exclude '*.hw/'
    --exclude '*.sim/'
    --exclude '.Xil/'
    --exclude '*.jou'
    --exclude '*.str'
    --exclude 'vivado_*.backup.log'
)

# Vitis: the BSP, FSBL and export trees are regenerated from the XSA.
#
# IMPORTANT: seven_segment_app/src is EXCLUDED. That directory holds
# hand-written application code whose source of truth is this repository, not
# the tool workspace. Syncing it in this direction once silently reverted the
# calculator application back to an older version that still lived in the
# workspace. Generated artefacts flow workspace -> repo; hand-written sources
# flow repo -> workspace, and must be copied there deliberately.
VITIS_EXCLUDES=(
    --exclude 'seven_segment_app/src/'
    --exclude '.metadata/'
    --exclude 'RemoteSystemsTempFiles/'
    --exclude 'zynq_fsbl/'
    --exclude 'ps7_cortexa9_0/'
    --exclude 'export/'
    --exclude 'Debug/'
    --exclude 'Release/'
    --exclude '.analytics'
    --exclude 'IDE.log'
)

sync_one() {
    local label="$1" src="$2" dst="$3"; shift 3
    if [ ! -d "$src" ]; then
        echo "  SKIP $label - not found: $src"
        return
    fi
    mkdir -p "$dst"
    rsync -a "${DELETE[@]}" "$@" "$src/" "$dst/"
    echo "  ok   $label -> ${dst#$REPO/}  ($(du -sh "$dst" | cut -f1))"
}

echo "syncing live projects into $LABS"

sync_one "lab1 task2 HLS" \
    "$HOME/vitis/lab1_task2/seven_segment_hls" \
    "$LABS/lab1/task2/hls" "${HLS_EXCLUDES[@]}"

sync_one "lab2 task1 HLS" \
    "$HOME/vitis/lab2_task1/lab2_task1_hls" \
    "$LABS/lab2/task1/hls" "${HLS_EXCLUDES[@]}"

sync_one "lab2 task1 Vivado" \
    "$HOME/vivado/lab2_calc" \
    "$LABS/lab2/task1/vivado" "${VIVADO_EXCLUDES[@]}"

sync_one "lab2 task2 Vitis" \
    "$HOME/vitis/lab2_task2_calc" \
    "$LABS/lab2/task2/vitis" "${VITIS_EXCLUDES[@]}"

echo
echo "labs tree is now $(du -sh "$LABS" | cut -f1)"
